import type { ContentProfile } from "@/lib/content/types";
import { createContentEntry } from "@/lib/content/generator";

const images = {
  sparkling: "/assets/menu/01-luna-tide.PNG",
  jasmine: "/assets/menu/02-night-nectar.PNG",
  milk: "/assets/menu/03-evenfall.PNG",
  oolong: "/assets/menu/04-clear-sky.PNG",
  fruit: "/assets/menu/06-monsoon.PNG",
  culture: "/assets/hero-home-final-v1-final.png"
} as const;

const articleProfiles: ContentProfile[] = [
  { slug: "sparkling-tea-singapore-guide", title: "Sparkling Tea in Singapore: A Modern Guide", description: "Understand sparkling tea, how it differs from soda and bubble tea, and what to look for in a refined Singapore tea experience.", category: "Sparkling Tea", focus: "sparkling tea", ingredients: "tea infusion, fine carbonation, fruit and botanicals", audience: "curious Singapore tea drinkers", localAngle: "A bright, tea-forward profile can feel especially refreshing in Singapore's warm, humid weather.", takeaway: "Choose balance and tea clarity over carbonation for its own sake.", keywords: ["sparkling tea Singapore", "modern tea", "tea guide"], heroImage: images.sparkling },
  { slug: "best-tea-singapore-how-to-choose", title: "How to Choose the Best Tea in Singapore", description: "A practical framework for comparing tea quality, sweetness, ingredients and serving style across Singapore.", category: "Singapore Tea", focus: "the best tea in Singapore", ingredients: "whole-leaf tea, water, fruit, milk and botanical accents", audience: "tea drinkers comparing cafés and menus", localAngle: "Singapore offers exceptional variety, so 'best' should reflect occasion and personal taste rather than a single ranking.", takeaway: "Judge the complete cup, not the loudest ingredient.", keywords: ["best tea Singapore", "tea shop Singapore", "premium tea"], heroImage: images.culture },
  { slug: "oriental-tea-modern-meaning", title: "What Modern Oriental Tea Means Today", description: "Explore how Oriental tea traditions can inspire contemporary drinks without losing clarity, restraint or cultural respect.", category: "Tea Culture", focus: "modern Oriental tea", ingredients: "Chinese tea traditions, contemporary technique and seasonal ingredients", audience: "drinkers interested in culture and modern design", localAngle: "Singapore's multicultural setting makes thoughtful adaptation particularly relevant.", takeaway: "Modern expression works best when it respects the tea beneath the presentation.", keywords: ["Oriental tea", "modern Chinese tea", "tea culture"], heroImage: images.culture },
  { slug: "jasmine-tea-aroma-flavour-guide", title: "Jasmine Tea: Aroma, Flavour and Quality", description: "Learn how jasmine tea is scented, how to recognise quality and why its floral character suits modern sparkling drinks.", category: "Jasmine Tea", focus: "jasmine tea", ingredients: "tea leaves scented with jasmine blossoms", audience: "floral-tea drinkers and first-time tasters", localAngle: "Jasmine's lifted aroma can remain expressive even when served chilled for Singapore weather.", takeaway: "Look for natural floral continuity rather than perfume-like intensity.", keywords: ["jasmine tea", "jasmine tea Singapore", "floral tea"], heroImage: images.jasmine },
  { slug: "oolong-tea-beginners-guide", title: "Oolong Tea for Beginners", description: "Discover oolong tea styles, oxidation, aroma and simple ways to choose an approachable first cup.", category: "Oolong Tea", focus: "oolong tea", ingredients: "partially oxidised tea leaves with floral, roasted or fruity expression", audience: "beginners exploring Chinese tea", localAngle: "Chilled oolong can retain structure while offering a clean option for warm afternoons.", takeaway: "Start with flavour families before worrying about regions or specialist terminology.", keywords: ["oolong tea guide", "Chinese tea Singapore", "oolong for beginners"], heroImage: images.oolong },
  { slug: "bubble-tea-alternatives-singapore", title: "Refreshing Bubble Tea Alternatives in Singapore", description: "Compare sparkling tea, fruit tea and tea-forward milk drinks as lighter alternatives to conventional bubble tea.", category: "Healthy Beverages", focus: "bubble tea alternatives", ingredients: "brewed tea, sparkling water, real fruit and measured sweetness", audience: "people seeking tea-forward refreshment", localAngle: "Singapore drinkers can choose lighter textures without giving up flavour or convenience.", takeaway: "An alternative is useful when it offers genuine tea character, not merely fewer toppings.", keywords: ["bubble tea alternatives Singapore", "healthy beverages", "sparkling tea"], heroImage: images.sparkling },
  { slug: "tea-for-students-focus-routine", title: "Tea for Students: Building a Better Study Routine", description: "A balanced guide to tea choices, hydration, timing and mindful study breaks for students.", category: "Tea Lifestyle", focus: "tea for students", ingredients: "moderately brewed tea, water and low-sweetness flavour accents", audience: "students building sustainable study habits", localAngle: "Long school days and warm commutes make hydration and sensible timing important in Singapore.", takeaway: "Tea can support a routine, but sleep, food and hydration remain fundamental.", keywords: ["tea for students", "study drink Singapore", "student tea"], heroImage: images.jasmine },
  { slug: "healthy-beverages-singapore-tea", title: "Healthy Beverage Choices: Where Tea Fits", description: "Learn how to assess sweetness, portions and ingredients when choosing tea-based beverages in Singapore.", category: "Healthy Beverages", focus: "healthy beverage choices", ingredients: "unsweetened tea, fruit, botanicals and transparent sweetening", audience: "health-conscious beverage shoppers", localAngle: "Frequent cold-drink occasions in Singapore make everyday sweetness awareness especially practical.", takeaway: "Healthfulness depends on the complete recipe and personal context, not a wellness label.", keywords: ["healthy beverages Singapore", "healthy tea", "low sugar drinks"], heroImage: images.fruit },
  { slug: "premium-tea-quality-signs", title: "Seven Signs of a Premium Tea Experience", description: "Identify the sensory, ingredient and service details that distinguish a genuinely premium tea experience.", category: "Premium Tea", focus: "premium tea quality", ingredients: "well-sourced tea, precise brewing and complementary ingredients", audience: "guests seeking a more refined tea experience", localAngle: "Premium tea in Singapore should remain enjoyable in real café conditions, not only in formal tastings.", takeaway: "Premium means coherence, consistency and care rather than ornament alone.", keywords: ["premium tea Singapore", "tea quality", "luxury tea"], heroImage: images.culture },
  { slug: "chinese-tea-types-explained", title: "Chinese Tea Types Explained Simply", description: "A clear introduction to green, white, yellow, oolong, black and dark Chinese tea categories.", category: "Chinese Tea", focus: "Chinese tea types", ingredients: "tea leaves shaped by oxidation, fixation, rolling and ageing", audience: "newcomers to Chinese tea", localAngle: "Singapore menus often combine several tea traditions, so category knowledge helps guests order confidently.", takeaway: "Processing category is a starting point, not a guarantee of one fixed flavour.", keywords: ["Chinese tea types", "Chinese tea Singapore", "tea categories"], heroImage: images.oolong },
  { slug: "tea-pairing-singapore-food", title: "Tea Pairing with Singapore Food", description: "Use aroma, sweetness, acidity and texture to pair tea with Singapore's diverse food culture.", category: "Tea Pairing", focus: "tea pairing with Singapore food", ingredients: "tea structure, carbonation, fruit acidity and food texture", audience: "diners who want tea to complement a meal", localAngle: "Singapore's hawker, café and restaurant flavours reward flexible pairing rather than rigid rules.", takeaway: "Use tea to refresh, bridge or contrast the dominant element on the plate.", keywords: ["tea pairing Singapore", "tea with food", "Singapore food drinks"], heroImage: images.fruit },
  { slug: "real-fruit-tea-ingredients", title: "Real Fruit in Tea: What It Changes", description: "Understand how real fruit affects aroma, acidity, sweetness, texture and consistency in modern tea drinks.", category: "Tea Ingredients", focus: "real fruit tea", ingredients: "fresh fruit, fruit purée, tea infusion and controlled sweetness", audience: "fruit-tea drinkers reading ingredient claims", localAngle: "Ripe tropical fruit is familiar in Singapore, but recipe balance still determines quality.", takeaway: "Real fruit adds complexity, yet it must remain in proportion with the tea.", keywords: ["real fruit tea", "fruit tea Singapore", "tea ingredients"], heroImage: images.fruit },
  { slug: "osmanthus-tea-flavour", title: "Osmanthus in Tea: A Gentle Floral Guide", description: "Explore osmanthus aroma, flavour pairings and its role in elegant modern tea compositions.", category: "Tea Ingredients", focus: "osmanthus tea", ingredients: "osmanthus blossom, jasmine tea, citrus and light fruit", audience: "drinkers who enjoy subtle floral flavours", localAngle: "Osmanthus offers fragrance without heaviness, making it suited to chilled Singapore tea service.", takeaway: "Its apricot-like floral note works best as a lift, not a dominant perfume.", keywords: ["osmanthus tea", "floral tea", "tea ingredients"], heroImage: images.sparkling },
  { slug: "sparkling-tea-vs-soda", title: "Sparkling Tea vs Soda: What Is the Difference?", description: "Compare tea base, flavour structure, sweetness, carbonation and serving occasions in sparkling tea and soda.", category: "Sparkling Tea", focus: "sparkling tea compared with soda", ingredients: "brewed tea, fine bubbles, fruit accents and optional sweetener", audience: "drinkers choosing between carbonated beverages", localAngle: "Both can be refreshing in Singapore, but tea offers aroma and finish beyond carbonation.", takeaway: "The defining difference is whether brewed tea remains central to the drink.", keywords: ["sparkling tea vs soda", "tea soda", "sparkling tea Singapore"], heroImage: images.sparkling },
  { slug: "sparkling-tea-vs-bubble-tea", title: "Sparkling Tea vs Bubble Tea", description: "Understand the differences in texture, toppings, tea intensity, sweetness and occasion between two popular drink styles.", category: "Sparkling Tea", focus: "sparkling tea compared with bubble tea", ingredients: "carbonation and tea clarity versus milk, toppings and chewy texture", audience: "Singapore beverage explorers", localAngle: "The two formats answer different cravings in Singapore's varied tea market.", takeaway: "Choose sparkling tea for lift and clarity, or bubble tea when texture is the main attraction.", keywords: ["sparkling tea vs bubble tea", "bubble tea Singapore", "tea alternatives"], heroImage: images.sparkling },
  { slug: "milk-tea-without-heavy-sweetness", title: "How Milk Tea Can Taste Light and Tea-Forward", description: "Learn how tea strength, milk choice, temperature and sweetness create a composed milk tea.", category: "Milk Tea", focus: "light, tea-forward milk tea", ingredients: "structured tea, fresh milk and restrained sweetness", audience: "milk-tea drinkers who prefer a cleaner finish", localAngle: "A lighter milk tea can feel more comfortable during Singapore's warm days and meal occasions.", takeaway: "Tea strength should lead while milk rounds the edges.", keywords: ["milk tea Singapore", "tea-forward milk tea", "fresh milk tea"], heroImage: images.milk },
  { slug: "macpherson-tea-guide", title: "A Tea Lover's Guide to MacPherson", description: "Plan a thoughtful tea stop around MacPherson Road and MacPherson Mall in Singapore.", category: "Singapore Tea", focus: "tea in MacPherson", ingredients: "sparkling tea, fruit tea, milk tea and local food pairings", audience: "residents, workers and visitors around MacPherson", localAngle: "MacPherson combines neighbourhood convenience, transport links and a lively mix of everyday food options.", takeaway: "Choose a tea stop that fits your route, meal and preferred level of sweetness.", keywords: ["MacPherson tea", "MacPherson bubble tea", "MacPherson Mall tea"], heroImage: images.culture },
  { slug: "tea-cafes-singapore-etiquette", title: "Tea Café Etiquette and Better Ordering", description: "Simple ways to order confidently, ask useful questions and enjoy a premium tea café in Singapore.", category: "Singapore Tea", focus: "tea café ordering", ingredients: "menu descriptions, sweetness choices, tea bases and seasonal specials", audience: "new and regular tea café guests", localAngle: "Singapore café service is informal and efficient, so concise preference-based questions work well.", takeaway: "Good ordering begins with taste preferences, not expert vocabulary.", keywords: ["tea cafés Singapore", "tea ordering", "premium tea café"], heroImage: images.culture },
  { slug: "tea-sweetness-levels-guide", title: "A Practical Guide to Tea Sweetness Levels", description: "Understand how sweetness changes aroma, acidity, bitterness and overall tea balance.", category: "Tea Ingredients", focus: "tea sweetness levels", ingredients: "sugar, fruit sweetness, milk sugars and tea polyphenols", audience: "drinkers adjusting sweetness preferences", localAngle: "Frequent iced-drink habits in Singapore make small sweetness changes meaningful over time.", takeaway: "Lower sweetness is not automatically better if the recipe loses balance.", keywords: ["tea sweetness levels", "less sugar tea", "healthy tea drinks"], heroImage: images.jasmine },
  { slug: "iced-tea-singapore-climate", title: "Why Iced Tea Works in Singapore's Climate", description: "Explore temperature, dilution, aroma and recipe design for iced tea in warm, humid weather.", category: "Singapore Tea", focus: "iced tea for Singapore's climate", ingredients: "concentrated tea, clean ice, fruit and controlled dilution", audience: "everyday iced-tea drinkers", localAngle: "Heat and humidity change serving needs, drinking pace and perceived sweetness.", takeaway: "A strong iced tea is designed for gradual dilution, not merely poured over ice.", keywords: ["iced tea Singapore", "cold tea", "Singapore weather drinks"], heroImage: images.fruit },
  { slug: "tea-and-botanicals", title: "Tea and Botanicals: Building Aroma Naturally", description: "Learn how flowers, herbs, citrus peel and spices can extend tea aroma without overwhelming it.", category: "Tea Ingredients", focus: "tea with botanicals", ingredients: "flowers, herbs, citrus peel, spice and brewed tea", audience: "drinkers curious about botanical beverages", localAngle: "Botanical lift can keep chilled tea expressive as ice melts in Singapore heat.", takeaway: "Every botanical should extend an existing tea note or create a deliberate contrast.", keywords: ["tea botanicals", "herbal tea ingredients", "premium tea"], heroImage: images.jasmine },
  { slug: "tea-tasting-beginners", title: "Tea Tasting for Beginners: Five Simple Steps", description: "Use aroma, first sip, texture, balance and finish to taste tea with more confidence.", category: "Tea Culture", focus: "beginner tea tasting", ingredients: "tea aroma, liquor, texture, sweetness and aftertaste", audience: "anyone who wants to taste more attentively", localAngle: "The method works for hot tea, iced tea and modern café drinks across Singapore.", takeaway: "Write down plain impressions before reaching for formal tasting terms.", keywords: ["tea tasting guide", "how to taste tea", "tea beginners"], heroImage: images.oolong },
  { slug: "tea-pairing-desserts", title: "How to Pair Tea with Desserts", description: "Balance sweetness, cream, fruit and chocolate with jasmine, oolong, sparkling and milk tea styles.", category: "Tea Pairing", focus: "tea pairing with desserts", ingredients: "floral tea, roasted oolong, fruit acidity and dessert sweetness", audience: "dessert lovers and café guests", localAngle: "Singapore's dessert scene ranges from traditional sweets to modern patisserie, inviting flexible tea pairings.", takeaway: "Choose a tea that is at least as aromatic as the dessert and cleaner on the finish.", keywords: ["tea dessert pairing", "tea pairing", "Singapore desserts"], heroImage: images.milk },
  { slug: "tea-pairing-spicy-food", title: "Tea Pairing with Spicy Food", description: "Choose tea temperature, sweetness, milk and carbonation to complement spicy dishes.", category: "Tea Pairing", focus: "tea pairing with spicy food", ingredients: "cool tea, gentle sweetness, milk texture and fruit acidity", audience: "diners enjoying chilli-forward meals", localAngle: "Spice is central to many Singapore meals, making beverage temperature and texture especially useful.", takeaway: "Refresh the palate without using excessive sweetness to fight heat.", keywords: ["tea with spicy food", "tea pairing Singapore", "spicy food drinks"], heroImage: images.fruit },
  { slug: "jasmine-tea-food-pairing", title: "Jasmine Tea Food Pairing Guide", description: "Pair jasmine tea with seafood, light savouries, fruit, pastry and Singapore dishes.", category: "Jasmine Tea", focus: "jasmine tea pairing", ingredients: "floral jasmine aroma, gentle tannin, citrus and delicate foods", audience: "jasmine-tea drinkers planning meals", localAngle: "Jasmine tea's aroma complements many lighter Singapore dishes without adding heaviness.", takeaway: "Pair by aromatic intensity and keep strongly smoky foods for more robust teas.", keywords: ["jasmine tea pairing", "tea with food", "jasmine tea Singapore"], heroImage: images.jasmine },
  { slug: "oolong-tea-food-pairing", title: "Oolong Tea Food Pairing Guide", description: "Match floral, roasted and fruity oolong styles with savoury meals, grilled foods and desserts.", category: "Oolong Tea", focus: "oolong tea pairing", ingredients: "floral oolong, roasted oolong, fruit notes and food texture", audience: "oolong drinkers exploring meal pairings", localAngle: "Oolong's range makes it adaptable to Singapore's diverse dining table.", takeaway: "Match lighter oolong with delicate foods and deeper roast with richer flavours.", keywords: ["oolong tea pairing", "oolong Singapore", "tea food pairing"], heroImage: images.oolong },
  { slug: "premium-tea-gift-guide", title: "A Thoughtful Premium Tea Gift Guide", description: "Choose tea gifts by taste, occasion, presentation and practical enjoyment rather than price alone.", category: "Premium Tea", focus: "premium tea gifts", ingredients: "quality tea, clear provenance, useful presentation and recipient preferences", audience: "gift buyers seeking a thoughtful tea choice", localAngle: "Tea is a versatile Singapore gift for visits, celebrations and professional occasions.", takeaway: "The best gift reflects how the recipient actually drinks tea.", keywords: ["premium tea gift Singapore", "tea gifts", "Chinese tea gift"], heroImage: images.culture },
  { slug: "tea-caffeine-explained", title: "Tea Caffeine Explained Without the Myths", description: "Understand how tea type, leaf quantity, time and serving size influence caffeine in a cup.", category: "Tea Benefits", focus: "caffeine in tea", ingredients: "tea leaves, water temperature, steep time and serving size", audience: "tea drinkers managing caffeine thoughtfully", localAngle: "Students and office workers in Singapore often drink tea across long days, so timing matters.", takeaway: "Tea category alone cannot predict exact caffeine; preparation and portion are essential.", keywords: ["tea caffeine", "caffeine in jasmine tea", "tea benefits"], heroImage: images.jasmine },
  { slug: "tea-hydration-balanced-view", title: "Tea and Hydration: A Balanced View", description: "Learn where tea fits within daily hydration and why sweetness, caffeine and personal needs matter.", category: "Tea Benefits", focus: "tea and hydration", ingredients: "water, brewed tea, caffeine and optional sweetener", audience: "people considering tea within daily hydration", localAngle: "Singapore heat increases the importance of regular fluid intake and practical beverage choices.", takeaway: "Tea can contribute fluid, but plain water and individual health guidance still matter.", keywords: ["tea hydration", "healthy tea", "tea benefits"], heroImage: images.fruit },
  { slug: "modern-tea-ritual-singapore", title: "Creating a Modern Tea Ritual in Singapore", description: "Build a simple daily tea ritual around attention, good ingredients and realistic routines.", category: "Tea Lifestyle", focus: "a modern tea ritual", ingredients: "a chosen tea, suitable cup, water and a few quiet minutes", audience: "busy people seeking a calmer beverage routine", localAngle: "A Singapore tea ritual must work around commutes, workdays, study and warm weather.", takeaway: "Consistency and attention matter more than elaborate equipment.", keywords: ["modern tea ritual", "tea lifestyle Singapore", "Oriental tea culture"], heroImage: images.culture }
];

const guideProfiles: ContentProfile[] = [
  { slug: "complete-guide-sparkling-tea", title: "The Complete Guide to Sparkling Tea", description: "A comprehensive guide to sparkling tea history, ingredients, production, tasting, pairing and modern Singapore service.", category: "Sparkling Tea", focus: "sparkling tea", ingredients: "tea extraction, carbonation, fruit, botanicals, ice and sweetness", audience: "drinkers, hosts and hospitality professionals", localAngle: "Singapore's climate and dining culture offer a natural setting for chilled, tea-forward sparkling drinks.", takeaway: "Great sparkling tea protects tea identity while using bubbles to create lift.", keywords: ["complete sparkling tea guide", "sparkling tea Singapore", "tea carbonation"], heroImage: images.sparkling },
  { slug: "complete-guide-chinese-tea", title: "The Complete Beginner's Guide to Chinese Tea", description: "Explore Chinese tea categories, processing, brewing, tasting and cultural context in one practical guide.", category: "Chinese Tea", focus: "Chinese tea", ingredients: "green, white, yellow, oolong, black and dark tea", audience: "beginners and returning tea drinkers", localAngle: "Singapore provides access to traditional tea and contemporary interpretations side by side.", takeaway: "Learn processing families first, then build knowledge through comparative tasting.", keywords: ["Chinese tea guide", "Chinese tea Singapore", "tea types"], heroImage: images.oolong },
  { slug: "singapore-premium-tea-guide", title: "The Complete Guide to Premium Tea in Singapore", description: "Navigate tea quality, cafés, menus, ingredients, pricing and service across Singapore's premium tea landscape.", category: "Singapore Tea", focus: "premium tea in Singapore", ingredients: "quality leaves, careful brewing, real ingredients and considered service", audience: "Singapore residents and visitors seeking refined tea", localAngle: "The city combines Chinese tea heritage, global café culture and modern beverage creativity.", takeaway: "Premium tea is best judged by clarity, consistency, hospitality and value.", keywords: ["premium tea Singapore", "best tea Singapore", "tea cafés Singapore"], heroImage: images.culture },
  { slug: "jasmine-tea-complete-guide", title: "The Complete Guide to Jasmine Tea", description: "A deep guide to jasmine scenting, tea bases, quality, brewing, tasting, pairing and chilled applications.", category: "Jasmine Tea", focus: "jasmine tea", ingredients: "jasmine blossoms, green or white tea bases, time and careful scenting", audience: "floral-tea enthusiasts and curious beginners", localAngle: "Jasmine tea remains expressive hot or chilled, making it versatile in Singapore.", takeaway: "Quality jasmine should smell integrated with tea rather than added on top.", keywords: ["jasmine tea complete guide", "jasmine tea Singapore", "floral tea"], heroImage: images.jasmine },
  { slug: "oolong-tea-complete-guide", title: "The Complete Guide to Oolong Tea", description: "Understand oolong oxidation, roast, origin, aroma, brewing, tasting and food pairing.", category: "Oolong Tea", focus: "oolong tea", ingredients: "partially oxidised leaf, skilled processing, roast and careful brewing", audience: "tea drinkers ready to explore oolong's range", localAngle: "Oolong adapts well to Singapore dining, from chilled fruit tea to traditional service.", takeaway: "Think of oolong as a broad craft family, not one flavour.", keywords: ["oolong tea complete guide", "oolong Singapore", "Chinese tea"], heroImage: images.oolong },
  { slug: "tea-pairing-complete-guide", title: "The Complete Guide to Tea and Food Pairing", description: "Master tea pairing through intensity, aroma, sweetness, acidity, texture and Singapore dining examples.", category: "Tea Pairing", focus: "tea and food pairing", ingredients: "tea body, aroma, temperature, carbonation and food structure", audience: "home diners, hosts and hospitality teams", localAngle: "Singapore's diverse cuisines provide an unusually rich pairing laboratory.", takeaway: "Pair the dominant sensory feature, then use tea to refresh or extend it.", keywords: ["tea pairing guide", "tea with food Singapore", "tea sommelier basics"], heroImage: images.fruit },
  { slug: "healthy-tea-beverages-guide", title: "A Practical Guide to Healthier Tea Beverages", description: "Assess sweetness, ingredients, portions, caffeine and marketing claims in modern tea beverages.", category: "Healthy Beverages", focus: "healthier tea beverages", ingredients: "brewed tea, water, fruit, milk, botanicals and measured sweetener", audience: "people seeking more informed everyday drink choices", localAngle: "Singapore's abundant cold-drink options make recipe literacy more useful than restrictive labels.", takeaway: "Choose transparent recipes and sustainable habits rather than chasing perfect beverages.", keywords: ["healthy tea drinks Singapore", "low sugar tea", "healthy beverages"], heroImage: images.fruit },
  { slug: "tea-culture-modern-singapore-guide", title: "Tea Culture in Modern Singapore: A Complete Guide", description: "Trace tea traditions, multicultural influences, cafés, modern beverages and everyday rituals in Singapore.", category: "Tea Culture", focus: "tea culture in modern Singapore", ingredients: "Chinese tea heritage, regional food culture, cafés and contemporary craft", audience: "readers interested in culture, design and hospitality", localAngle: "Singapore's tea identity emerges from many communities and continues to evolve.", takeaway: "Respect for tradition and openness to modern expression can coexist.", keywords: ["tea culture Singapore", "Singapore tea history", "modern Oriental tea"], heroImage: images.culture },
  { slug: "tea-ingredients-complete-guide", title: "The Complete Guide to Modern Tea Ingredients", description: "Understand tea bases, fruit, flowers, herbs, milk, sweeteners, carbonation and texture in contemporary drinks.", category: "Tea Ingredients", focus: "modern tea ingredients", ingredients: "tea, fruit, botanicals, milk, sweeteners, bubbles and inclusions", audience: "curious consumers and beverage creators", localAngle: "Singapore's ingredient diversity makes transparent composition especially valuable.", takeaway: "Ingredients create quality only when their roles are clear and proportionate.", keywords: ["tea ingredients guide", "fruit tea ingredients", "premium tea"], heroImage: images.sparkling },
  { slug: "student-tea-wellbeing-guide", title: "The Complete Student Guide to Tea and Wellbeing", description: "A responsible guide to tea, caffeine, hydration, study routines, sleep and affordable choices for students.", category: "Tea Lifestyle", focus: "tea and student wellbeing", ingredients: "moderate tea, water, sensible sweetness, food and rest", audience: "students and families building balanced routines", localAngle: "Singapore students often manage long schedules, warm travel and demanding study periods.", takeaway: "Tea may complement a routine, but it cannot replace sleep, nutrition, movement or medical advice.", keywords: ["tea for students", "student wellbeing Singapore", "study tea"], heroImage: images.jasmine }
];

function relatedFor(profiles: ContentProfile[], index: number) {
  return [1, 2, 3].map((offset) => profiles[(index + offset) % profiles.length].slug);
}

export const articles = articleProfiles.map((profile, index) => createContentEntry(profile, "article", index, relatedFor(articleProfiles, index)));
export const guides = guideProfiles.map((profile, index) => createContentEntry(profile, "guide", index, relatedFor(guideProfiles, index)));
export const allContent = [...articles, ...guides];

export const categories = Array.from(
  allContent.reduce((map, entry) => {
    const current = map.get(entry.categorySlug) ?? { name: entry.category, slug: entry.categorySlug, count: 0 };
    current.count += 1;
    map.set(entry.categorySlug, current);
    return map;
  }, new Map<string, { name: string; slug: string; count: number }>()).values()
).sort((a, b) => a.name.localeCompare(b.name));

export function getArticle(slug: string) {
  return articles.find((entry) => entry.slug === slug);
}

export function getGuide(slug: string) {
  return guides.find((entry) => entry.slug === slug);
}

export function getCategory(slug: string) {
  return categories.find((category) => category.slug === slug);
}

export function getRelatedContent(entry: (typeof allContent)[number]) {
  const pool = entry.kind === "article" ? articles : guides;
  return entry.relatedSlugs.map((slug) => pool.find((candidate) => candidate.slug === slug)).filter((candidate): candidate is (typeof pool)[number] => Boolean(candidate));
}

export function getContentSeoImage(entry: (typeof allContent)[number]) {
  const isHomepageHero = entry.heroImage.includes("hero-home");
  return {
    url: entry.heroImage,
    width: isHomepageHero ? 1672 : 1536,
    height: isHomepageHero ? 941 : 1024,
    alt: entry.heroAlt
  };
}
