import type { ContentEntry } from "./types";

// Individually authored replacements. The old URL is retained; the repeated
// filler generator is never used for these published entries.
type Draft = {
  slug: string; kind?: "article" | "guide"; title: string; zhTitle: string;
  summary: string; zhSummary: string; category: string;
  en: string; zh: string; photo: string; showStore?: boolean;
  sources?: { title: string; url: string }[];
};
const museum = { title: "Hong Kong Museum of Tea Ware: Chinese tea categories", url: "https://www.info.gov.hk/gia/general/201209/11/P201209110260.htm" };
const drafts: Draft[] = [
  {
    slug: "best-tea-singapore-how-to-choose", title: "Choosing Tea in Singapore: A Personal Comparison", zhTitle: "新加坡选茶：找到适合自己的那一杯",
    summary: "Compare the occasion, drink description and actual price before deciding which tea suits you.", zhSummary: "从场合、茶饮介绍与实际价格出发，比较适合自己的选择。", category: "Singapore Tea", photo: "store-welcome-v5",
    en: "## Define what a good cup means today\n\nA quick takeaway, a drink alongside lunch and tea for a meeting are different purchases. Write down your priority: a sparkling texture, a familiar flavour, a still drink or a budget. This makes a comparison more useful than an unsupported city-wide ranking.\n\n## Compare the whole purchase\n\nRead the drink description and the price conditions together. Member pricing should not be compared with another regular price as if the conditions were identical. Include any separately quoted fulfilment cost when planning a group request.\n\n## Keep one useful note\n\nAfter drinking, note what you liked and what you would change next time. Your own preference is better evidence for your next purchase than a photograph or an adjective such as premium. At QING YUN JIAN, begin with the current menu below.",
    zh: "## 今天的好茶，先由场合决定\n\n外带一杯、配午餐喝、会议用茶，是不同的购买场合。先写下最在意的一点：气泡触感、熟悉的风味、无气泡饮品，或预算。这样比没有依据的全城排名更能帮助选择。\n\n## 比较整份购买条件\n\n茶饮介绍与价格条件要一起看。会员价格不能与普通价格直接当作相同条件比较；团单如有另外报价的领取或配送费用，也应算进预算。\n\n## 留下一条自己的记录\n\n喝完记下喜欢的地方，以及下次想调整什么。自己的偏好，比照片或“高级”这样的形容词更能帮助下一次选择。到青云间选茶，可以从下方现行菜单开始。"
  },
  {
    slug: "oriental-tea-modern-meaning", title: "Modern Oriental Tea: What We Mean at QING YUN JIAN", zhTitle: "现代东方茶：青云间怎样理解这句话",
    summary: "Our brand direction connects tea with contemporary drink choices, design and everyday occasions.", zhSummary: "认识青云间的品牌方向，以及茶饮、设计与日常场合之间的联系。", category: "Tea Culture", photo: "store-pegasus-photo-v3",
    en: "## A brand direction, not a historical category\n\nModern Oriental tea is QING YUN JIAN's positioning. It describes a contemporary expression inspired by Oriental tea culture; it is not a claim that we invented a traditional tea classification. Our brand originated in Singapore and was founded in 2026.\n\n## Read the cup as well as the design\n\nThe Pegasus expresses aspiration and upward movement. That meaning belongs to the brand identity. To understand a particular drink, use its current description instead: a symbol or a poetic name cannot establish ingredients, preparation or flavour.\n\n## Explore the idea in everyday use\n\nTry a cup during a visit, or explore the story behind the brand through Our Story. For a team gathering, the practical questions remain the drinks, quantities and arrangements. The modern expression should help people choose and share tea without requiring specialist vocabulary.",
    zh: "## 品牌方向，不是传统茶类名称\n\n“现代东方茶”是青云间的品牌定位，表达受东方茶文化启发的当代茶饮方式，并不代表我们创造了某一种传统茶类。青云间源自新加坡，创立于 2026 年。\n\n## 看设计，也看杯中的资料\n\n飞马表达向上、志向与升腾，是品牌的象征。了解某一杯茶，仍要查看当前介绍；图案或诗意名称不能代替原料、制作方式与口味说明。\n\n## 把理念放回日常\n\n可以到店选一杯，也可以通过“我们的故事”了解品牌想法。团队聚会则仍需确定茶品、数量与安排。现代的表达，应让人更容易选择和分享茶，而不是要求客人先懂一套专业术语。"
  },
  {
    slug: "jasmine-tea-aroma-flavour-guide", title: "Choosing a Jasmine Tea Drink by Aroma", zhTitle: "选茉莉茶饮，从香气说起",
    summary: "Describe the floral character you enjoy and check what accompanies the tea in the actual drink.", zhSummary: "说清自己喜欢的花香，再查看这杯茶还有哪些搭配。", category: "Jasmine Tea", photo: "store-cups-photo-v3",
    en: "## Start with a plain description\n\nIf you enjoy floral drinks, say whether you want the floral note to stand out or sit behind another flavour. You do not need to identify a grade or use tasting jargon to ask a useful question.\n\n## Separate the tea from its companions\n\nA jasmine-led drink can still have fruit, milk or other elements. Read the individual description rather than assuming that the word jasmine tells you everything in the cup. Ask about any ingredient that affects your decision.\n\n## Compare one impression at a time\n\nNotice the first aroma, then the flavour of a sip, then the texture. If two drinks differ in several ways, record those differences instead of treating the comparison as a test of tea quality alone. The current QING YUN JIAN descriptions below help you choose what to explore.",
    zh: "## 用简单的话说出偏好\n\n喜欢花香饮品，可以先说明希望花香突出，还是作为其他风味的背景。不需要先懂等级或品茶术语，也能提出有用的问题。\n\n## 茶底与搭配分开看\n\n以茉莉风味为主的饮品，也可能搭配水果、奶或其他元素。应阅读单款介绍，不要把“茉莉”两个字当作整杯原料表；会影响选择的原料，应另外询问。\n\n## 一次比较一个感受\n\n先留意闻到的香气，再尝一口的味道，最后感受触感。两杯饮品若有多处不同，应分别记录，而不是当作只比较茶叶质量。下方青云间的现行介绍可以帮助您决定先试哪一杯。"
  },
  {
    slug: "oolong-tea-beginners-guide", title: "Your First Oolong Drink: Three Ordering Questions", zhTitle: "第一次选乌龙茶饮：三个点单问题",
    summary: "Ask what tea is listed, what accompanies it and which preparation options are available.", zhSummary: "确认茶品介绍、搭配元素与可提供的制作选项。", category: "Oolong Tea", photo: "store-working-counter-v5",
    en: "## Which tea does this drink list?\n\nStart with the menu description. A broad term such as oolong is a useful starting point, but it does not establish the exact tea specification or sourcing. Ask the team for the current information if you want more detail.\n\n## What else will I taste?\n\nLook for any listed fruit, milk or other accompaniment. A finished drink and a plain tea are different things to compare. If you want to notice the tea more clearly, describe that preference and ask which current choice fits it.\n\n## What can the store adjust?\n\nAsk about the options offered for that particular drink, rather than assuming a standard set of adjustments. Keep a note of the tea name and the version you actually ordered. That gives you a useful reference when exploring another oolong drink later.",
    zh: "## 这杯介绍的是哪一种茶？\n\n先阅读菜单。乌龙这样的广义名称是入门线索，但不能确定具体茶叶规格或来源。希望了解更多，可以向团队询问现行资料。\n\n## 除了茶，还会尝到什么？\n\n查看是否列有水果、奶或其他搭配。调制后的茶饮与单纯的茶，是不同的比较对象。希望更明显地感受到茶，可以直接描述偏好，再询问现时哪一款较合适。\n\n## 门店可以调整什么？\n\n针对单款询问可提供的选项，不要假设每款都能作同样调整。记下茶名与实际点的版本，之后探索另一杯乌龙茶饮时，就有清楚的比较依据。"
  },
  {
    slug: "bubble-tea-alternatives-singapore", title: "Beyond Bubble Tea: Choose a Different Texture", zhTitle: "珍珠茶之外：从另一种口感开始选",
    summary: "Explore sparkling, still and milk-based choices without assuming that a category promises a nutritional benefit.", zhSummary: "按气泡、无气泡与奶感选茶，让口感偏好带路。", category: "Tea Lifestyle", photo: "store-packaging-wide-v4",
    en: "## Decide what you want to change\n\nIf your usual drink has toppings, ask whether you want a different texture, a different flavour or simply a new tea base. These are separate choices. Changing all of them at once can make it harder to learn what you enjoy.\n\n## Look at the actual options\n\nA sparkling drink offers bubbles in the liquid; a still drink avoids that sensation. A milk-based drink offers another direction. Check the current menu for which styles are actually available rather than relying on an old image.\n\n## Keep the comparison honest\n\nA different category does not prove a drink has less sugar or different nutritional values. Use the specific description and ask the store about details that matter. For an office order, collect preferences before choosing a single alternative for everyone.",
    zh: "## 先想清楚想换什么\n\n平常喝带配料的茶，可以先问自己：想换触感、风味，还是茶底？这些是不同选择。全部一起换，反而不容易知道自己真正喜欢哪个变化。\n\n## 看现时有哪些选择\n\n气泡饮品的气泡在液体里，无气泡饮品则没有这种触感；奶类茶饮又是另一个方向。请查看现行菜单确认可售款式，不要只凭旧图片决定。\n\n## 比较时说清依据\n\n类别不同，不能证明糖量更少或营养值不同。应阅读具体介绍，重要细节向门店询问。办公室订茶时，也宜先收集偏好，再决定是否统一换成同一种饮品。"
  },
  {
    slug: "tea-for-students-focus-routine", title: "A Student Tea Break: Plan the Purchase", zhTitle: "学生茶歇：把点单安排好",
    summary: "A practical purchase checklist for friends sharing a tea break, with current prices and clear choices.", zhSummary: "朋友一起买茶，先看现价、收集选择，再把点单整理好。", category: "Tea Lifestyle", photo: "store-interior-photo-v3",
    en: "## Set a budget before choosing\n\nLook at the regular price for each drink. If you see a student promotion, read its current dates and eligibility rather than assuming an old poster still applies. A membership price has its own conditions.\n\n## Collect names and choices\n\nFor friends ordering together, note who wants which drink and any questions to ask the store. Keep ingredient questions separate from taste preferences so they can be answered before purchase.\n\n## Fit the stop into the day\n\nCheck the visit page before setting off and allow time for your own route. This article helps organise a purchase; it does not claim that tea improves concentration or study performance. Larger planned gatherings can use the group-order request and wait for confirmation.",
    zh: "## 先定预算，再选茶\n\n查看每款普通价格。看到学生优惠时，应阅读当前日期与适用条件，不能假设旧海报仍然有效；会员价也有自己的条件。\n\n## 记录名字与选择\n\n朋友一起买，可以写清谁选哪款，以及需要问门店的问题。原料问题与口味偏好应分开记录，在购买之前确认。\n\n## 把到店放进当天安排\n\n出发前查看到店页面，给自己的路线留出时间。这篇文章帮助安排购买，不宣称茶能提高专注或学习表现。较大型的计划聚会，可以提交团体订购申请，再等团队确认。"
  },
  {
    slug: "healthy-beverages-singapore-tea", title: "Before Choosing a 'Healthy' Tea: Read the Drink Details", zhTitle: "看到“健康茶饮”时，先看具体资料",
    summary: "Turn a broad marketing label into clear questions about the actual drink you are considering.", zhSummary: "把笼统的宣传词，变成针对这杯饮品的具体问题。", category: "Tea Ingredients", photo: "store-packaging-portrait-v4",
    en: "## A label is not a specification\n\nWords such as healthy, natural or light do not supply an ingredient list or measured nutritional values. When a detail matters to you, look for actual product information instead of making an inference from colour, branding or category.\n\n## Write down what you need to know\n\nAsk about the current ingredients, offered adjustments and any documented information relevant to your purchase. State the question clearly. An adjustment option should not be treated as a measured nutritional result.\n\n## Know the limit of a menu\n\nThis is a guide to reading drink information, not a health recommendation. QING YUN JIAN's current catalogue can show descriptions, prices and availability. If it does not answer a question, seek confirmation before ordering rather than filling the gap with a general tea claim.",
    zh: "## 宣传词不是产品规格\n\n“健康”“天然”“轻盈”等词，没有提供完整原料表或实测营养数值。某个细节对您重要时，应查看实际资料，不要从颜色、包装或类别自行推断。\n\n## 写清需要知道什么\n\n可以询问现行原料、可提供的调整，以及与购买有关的已记录资料。问题越具体，越容易确认；能调整某个选项，也不能当作已经测定的营养结果。\n\n## 了解菜单的范围\n\n这是一份阅读产品资料的指南，不是健康建议。青云间的现行目录可以列出介绍、价格与供应状态；页面没有回答的问题，应在订购前确认，不宜用一般茶饮宣传补上空缺。"
  },
  {
    slug: "premium-tea-quality-signs", title: "Seven Things to Check Before Paying for Premium Tea", zhTitle: "买“高级茶饮”前，可核对的七件事",
    summary: "Use clear product information and your own tasting notes to assess a purchase.", zhSummary: "用清楚的产品资料和自己的品尝记录判断购买价值。", category: "Premium Tea", photo: "store-welcome-v5",
    en: "## Check information before adjectives\n\nPremium is a description, not a universal grading system for prepared drinks. Before paying more, identify what is actually being offered.\n\n- The name of the drink.\n- Its current description.\n- Its listed category.\n- The regular price.\n- Conditions for a member or promotional price.\n- Current availability.\n- Answers to your ingredient or preparation questions.\n\n## Assess the experience you receive\n\nAfter purchase, note whether the description helped you choose and whether you enjoyed the cup. Keep service, presentation and flavour as separate observations. A beautiful package does not establish sourcing or a recipe.\n\n## Use that evidence next time\n\nYour notes can guide a repeat order or a different choice. They should not become an unsupported ranking of every tea shop in Singapore. Open the QING YUN JIAN drink pages below to check the information available today.",
    zh: "## 先核对资料，再看形容词\n\n“高级”是描述，并不是所有调制饮品共用的等级标准。决定付多少钱之前，先确认实际提供什么。\n\n- 茶品名称。\n- 当前介绍。\n- 所属系列。\n- 普通价格。\n- 会员价或活动价的条件。\n- 现时供应状态。\n- 原料或制作问题的答复。\n\n## 判断实际体验\n\n购买后，可以记下介绍是否帮助选茶，以及自己是否喜欢这杯。服务、外观与风味分开评价；漂亮包装不能证明来源或配方。\n\n## 把依据留给下一次\n\n这些记录可以帮助回购或尝试另一款，但不宜变成对全新加坡茶店没有依据的排名。下方青云间茶品页可以查看今天可提供的资料。"
  },
  {
    slug: "chinese-tea-types-explained", title: "Chinese Tea Names: Category, Ingredient or Finished Drink?", zhTitle: "中国茶名：茶类、原料还是调制饮品？",
    summary: "Separate processing categories from flavour descriptions when reading a modern tea menu.", zhSummary: "阅读现代茶饮菜单时，把茶类名称与风味说明分开。", category: "Chinese Tea", photo: "store-working-counter-v5", sources: [museum],
    en: "## Tea categories describe processing\n\nThe Hong Kong Museum of Tea Ware describes six main types according to processing: green, black, oolong, white, yellow and pu'er tea. This is a useful introductory framework, not a list of everything offered at QING YUN JIAN.\n\n## A menu adds other layers\n\nA finished drink can have a tea base, accompanying ingredients and a serving style. Read these layers separately. A category name does not identify every ingredient or tell you whether the drink is sparkling.\n\n## Ask a precise follow-up\n\nIf you want to explore the tea base, ask which tea the current drink description lists. If you want to avoid a particular ingredient, ask about that ingredient instead. Those questions answer different needs. The current menu below is the starting point for QING YUN JIAN choices.",
    zh: "## 茶类说明加工分类\n\n香港茶具文物馆以加工方式介绍六大类：绿茶、红茶、乌龙茶、白茶、黄茶及普洱茶。这是入门分类，并不是青云间提供全部这些茶类的意思。\n\n## 菜单还有其他层次\n\n一款调制饮品可以有茶底、搭配原料与饮用形式，应分别阅读。茶类名称不能说明所有原料，也不能告诉您饮品是否带气泡。\n\n## 针对需要追问\n\n想探索茶底，可以询问现行介绍列的是哪一种茶。希望避免某种原料，则应直接问该原料。这些问题解决的是不同需要；选择青云间茶饮时，可先查看下方现行菜单。"
  },
  {
    slug: "tea-pairing-singapore-food", title: "Tea with Singapore Food: Try One Pairing at a Time", zhTitle: "茶配新加坡美食：一次试一个搭配",
    summary: "A personal tasting exercise for choosing a drink with your meal, without rigid pairing rules.", zhSummary: "用简单的品尝练习，为自己的餐点选茶。", category: "Tea Pairing", photo: "store-packaging-wide-v4",
    en: "## Choose the meal first\n\nWrite down the dish you will actually eat, rather than choosing a drink for an entire cuisine. A noodle lunch and a dessert stop can lead to different preferences even at the same venue.\n\n## Try a small comparison\n\nTake a sip before eating, then another after a mouthful. Notice whether you prefer the combination to the drink alone. This is a personal tasting exercise; there is no requirement that a particular tea must accompany a particular Singapore dish.\n\n## Remember the practical details\n\nFor takeaway, consider where and when you will receive the food and drink. For a meeting with meals, record the serving time in a group enquiry. QING YUN JIAN confirms drink availability and fulfilment separately; this article does not promise food service or a catering package.",
    zh: "## 先决定实际餐点\n\n记录要吃的那一道菜，不必为整个菜系统一选茶。同一家店的面食午餐与甜点时段，也可能有不同偏好。\n\n## 做一个小比较\n\n吃之前先喝一口，吃一口食物之后再喝，看看自己是否更喜欢这样的组合。这是个人品尝练习，没有规定某种茶一定要搭配某一道新加坡菜。\n\n## 记住实际安排\n\n外带时要考虑食物与茶饮在哪里、什么时候领取。配餐会议可以在团单备注写明供应时间。青云间需另行确认茶品与执行安排；这篇文章没有承诺供餐或餐饮套餐。"
  },
  {
    slug: "real-fruit-tea-ingredients", title: "Reading Fruit Tea Descriptions: Ask About the Form", zhTitle: "看水果茶介绍：问清水果以什么形式加入",
    summary: "A fruit name alone does not tell you how the ingredient is used in a prepared drink.", zhSummary: "水果名称本身，不能说明它在饮品中的实际使用形式。", category: "Tea Ingredients", photo: "store-cups-photo-v3",
    en: "## Separate flavour from ingredient form\n\nA fruit name can describe a flavour without giving a complete recipe. If preparation matters to you, ask whether the current information identifies pieces, juice, purée or another form. Do not infer the answer from visible garnish.\n\n## Ask about the whole drink\n\nFruit is only one part of a fruit tea. Check the listed tea base and other elements as well. A photograph cannot establish amounts, sweetness or ingredient sourcing. The store can clarify what information is available for the current version.\n\n## Record the version you ordered\n\nKeep the drink name and any agreed adjustment together. That makes your next comparison more useful than remembering only the fruit. For a group order, send unresolved ingredient questions before final agreement rather than assuming all fruit drinks are interchangeable.",
    zh: "## 风味与原料形式分开看\n\n水果名称可以描述风味，却未必提供完整配方。如果在意制作方式，可以询问现行资料有没有说明果粒、果汁、果泥或其他形式；不应凭杯面装饰推断。\n\n## 询问整杯饮品\n\n水果只是水果茶的一部分，还应查看茶底及其他搭配。照片不能证明用量、甜度或原料来源；门店可以说明当前版本有哪些可提供的资料。\n\n## 记录实际点的版本\n\n把茶名与双方同意的调整记在一起，比只记得水果名称更方便下次比较。团单需要确认的原料问题，应在最终确认前提出，不要假设不同水果茶可以随意互换。"
  },
  {
    slug: "osmanthus-tea-flavour", title: "Exploring Osmanthus in a Tea Drink", zhTitle: "在茶饮里认识桂花风味",
    summary: "Follow the current description and compare aroma, texture and accompanying flavours separately.", zhSummary: "按现行介绍认识桂花搭配，分别感受香气、触感与其他风味。", category: "Tea Ingredients", photo: "sparkling-tea-detail-v3",
    en: "## Read how it is described\n\nWhen a drink description mentions osmanthus, look at the rest of the wording. A flavour, a jelly and another preparation are not the same specification. The name alone does not establish the ingredient form or amount.\n\n## Notice separate elements\n\nTry describing the aroma independently from any texture you feel. Then notice the other flavours in the cup. This helps you tell the team which part you enjoyed without needing a botanical explanation or an invented tasting note.\n\n## Confirm the current version\n\nUse the individual QING YUN JIAN page and ask the store about any detail not recorded there. Recipes and offered options should be checked for the actual purchase. This guide does not promise a particular osmanthus ingredient in every drink or claim a health effect.",
    zh: "## 看清介绍怎样写\n\n茶品介绍提到桂花时，也要看后面的说明。风味、冻类配料与其他制作形式，不是同一种规格；名称本身不能确定形式或用量。\n\n## 分开感受不同元素\n\n可以把闻到的香气与入口的触感分开描述，再留意杯中的其他风味。这样容易向团队说清喜欢哪一部分，不需要先懂植物知识，也不必套用别人的品尝词。\n\n## 确认现行版本\n\n查看青云间的单款页面，未记录的细节可以问门店。配方与选项应针对实际购买确认；本指南不承诺每杯都有特定桂花原料，也不宣称健康效果。"
  },
  {
    slug: "sparkling-tea-vs-soda", title: "Sparkling Tea and Soda: Compare the Actual Drinks", zhTitle: "气泡茶与汽水：比较实际饮品",
    summary: "Check the tea description, other ingredients and serving conditions rather than judging by bubbles alone.", zhSummary: "查看茶的介绍、其他原料与供应条件，不只看有没有气泡。", category: "Sparkling Tea", photo: "sparkling-tea-detail-v3",
    en: "## Bubbles are only one part\n\nTwo carbonated drinks can have a similar sparkling sensation while offering different flavours. For a sparkling tea, read what the menu says about the tea. For another drink, read its own description or label.\n\n## Make a fair comparison\n\nCompare actual servings and price conditions. A name does not prove sugar content, caffeine or other nutritional values. If those details determine your choice, seek the specific product information rather than declaring one whole category better.\n\n## Choose for this occasion\n\nYou may want to explore a tea-led drink at lunch or choose a familiar taste for a gathering. Record that preference instead of treating the choice as a universal rule. QING YUN JIAN's current drink pages show the information available for its own menu.",
    zh: "## 气泡只是其中一部分\n\n两种带气泡的饮品，可能有相似触感，却有不同风味。看气泡茶时应阅读菜单如何介绍茶；看另一种饮品，则阅读它自己的介绍或标签。\n\n## 在相同条件下比较\n\n比较实际份量与价格条件。名称不能证明糖量、咖啡因或其他营养数值；这些细节会影响选择时，应找具体资料，不宜宣布整个类别更好。\n\n## 为这一次场合选择\n\n午餐可能想探索茶风味，聚会可能想选熟悉口味。把偏好写清，比当作人人适用的规则更有帮助。青云间的现行茶品页列有自己菜单可提供的资料。"
  },
  {
    slug: "milk-tea-without-heavy-sweetness", title: "Ordering Milk Tea When You Want the Tea to Stand Out", zhTitle: "想让茶味更突出，奶茶可以这样问",
    summary: "Describe your preference and check available adjustments for the particular milk tea.", zhSummary: "说清茶味偏好，再针对单款确认可提供的调整。", category: "Milk Tea", photo: "store-cups-photo-v3",
    en: "## Describe the balance you prefer\n\nTell the team that you want to notice the tea, rather than asking for a vague light drink. If you have a previous favourite, explain what you liked about it: the aroma, milk character or finish.\n\n## Check the listed composition\n\nRead the current milk tea description. The menu name does not establish the milk type, exact amount or every ingredient. Ask for confirmation if any of these details affect your purchase.\n\n## Agree adjustments before ordering\n\nFind out which changes are offered for that drink. A sweetness setting cannot by itself tell you the final nutritional values. When ordering several cups, record the agreed choices clearly so an organiser does not combine different requests into one ambiguous note.",
    zh: "## 把喜欢的平衡说清楚\n\n可以告诉团队，希望喝到较明显的茶味，比笼统地说“轻一点”更清楚。若有以前喜欢的一杯，可以说明喜欢的是香气、奶感还是尾韵。\n\n## 查看列出的搭配\n\n阅读当前奶茶介绍。菜单名称不能确定奶的种类、准确用量或全部原料；这些会影响购买时，应先确认。\n\n## 点单之前商量调整\n\n询问该款可提供哪些变化。甜度设置本身不能说明最终营养数值。一次买多杯时，应逐项记录双方同意的选择，避免负责人把不同要求合成一句含糊的备注。"
  },
  {
    slug: "tea-cafes-singapore-etiquette", title: "Better Tea Ordering: Four Clear Questions", zhTitle: "点茶更清楚：四个实用问题",
    summary: "Ask about the current drink, price, availability and arrangements without needing specialist knowledge.", zhSummary: "不需要专业知识，也能问清茶品、价格、供应与安排。", category: "Singapore Tea", photo: "store-working-counter-v5",
    en: "## Ask about the drink first\n\nStart with your preference and the name of the drink you are considering. For example: I enjoy sparkling texture; what does this description include? If an ingredient matters, name it directly.\n\n## Check the purchase conditions\n\n- Is this drink currently available?\n- Is the displayed amount the regular or member price?\n- Which adjustments can be offered for this drink?\n- Where should I collect it, or how will a planned request be confirmed?\n\n## Keep group questions together\n\nFor an office enquiry, have one organiser collect the drink list and unresolved questions. The website form can record the request, but availability, timing and quotation still require confirmation. Clear questions reduce misunderstandings more effectively than elaborate tasting language.",
    zh: "## 先问正在考虑的茶品\n\n从偏好与茶名开始，例如：“我喜欢气泡触感，这杯介绍包括哪些搭配？”在意某种原料，可以直接点名询问。\n\n## 核对购买条件\n\n- 这款现在可以供应吗？\n- 标示金额是普通价还是会员价？\n- 这款可以作哪些调整？\n- 在哪里领取，或计划中的申请怎样确认？\n\n## 团单问题集中整理\n\n办公室询问宜由一位负责人收集清单与未解决的问题。网站表格可以记录申请，但供应、时间与报价仍须确认。清楚的问题，比复杂的品茶用语更能减少误会。"
  },
  {
    slug: "tea-sweetness-levels-guide", title: "Tea Sweetness Settings: What to Confirm", zhTitle: "茶饮甜度选项：先确认什么",
    summary: "Clarify available options and record your actual order instead of assuming a percentage describes the whole recipe.", zhSummary: "问清可提供的选项，记录实际点单，不把百分比当作完整配方。", category: "Tea Ingredients", photo: "store-packaging-wide-v4",
    en: "## Ask what the setting changes\n\nA sweetness label is an ordering instruction, not necessarily a measurement of the entire drink. Ask what it applies to in the particular recipe. Do not assume the same label means the same preparation across different shops.\n\n## Check which options exist\n\nThe current drink may have different adjustment options from another item. Confirm what can be offered before submitting an order, especially when somebody else is buying for you.\n\n## Record a useful comparison\n\nKeep the drink name and agreed setting together. At your next visit, change one preference if you want to compare the experience. For a group request, identify the cups affected by each request and ask the team to confirm feasibility rather than placing a blanket instruction on the entire order.",
    zh: "## 问清这个设置调整什么\n\n甜度标签是点单要求，未必是整杯饮品的实测数值。应问清在该配方中调整的是哪一部分，也不要假设不同门店的相同标签代表同样做法。\n\n## 确认有哪些选项\n\n不同茶品可能有不同调整范围。订购之前确认可以提供什么，尤其是由别人代买时。\n\n## 留下有用的比较记录\n\n把茶名与双方同意的设置写在一起。下次想比较体验，可以只改一个偏好。团单应说明每项要求涉及哪些杯，并请团队确认能否安排，不宜给全部饮品放一条笼统要求。"
  },
  {
    slug: "iced-tea-singapore-climate", title: "Iced Tea on the Go: Plan the Handover", zhTitle: "外带冰茶：把领取时间安排好",
    summary: "Think about collection, travel and serving time when choosing tea for yourself or a team.", zhSummary: "个人或团队买茶，把领取、路程与饮用时间一起考虑。", category: "Singapore Tea", photo: "store-packaging-portrait-v4",
    en: "## Start with when you will drink it\n\nA drink for immediate enjoyment and a drink collected before an event involve different arrangements. Tell the organiser or store when you expect to serve it instead of discussing only the collection time.\n\n## Check the route yourself\n\nUse the current visit page and map link to plan your journey. This guide does not estimate travel time, queue length or a guaranteed collection slot. If timing is important, ask the team to confirm what is possible.\n\n## Keep the handover simple\n\nFor a group, name one receiving person and keep the agreed drink list available. Ask the store about any handling instructions appropriate to the actual drinks. Do not reuse an old arrangement without checking current availability and the event's schedule.",
    zh: "## 先想什么时候喝\n\n买了马上喝，与提前为活动领取，是不同安排。除领取时间之外，也应向负责人或门店说明预计什么时候分发饮用。\n\n## 自己核对路线\n\n使用现行到店页面与地图规划行程。本指南不估计路程、排队时间，也不保证某个领取时段；时间重要时，应请团队确认能否配合。\n\n## 交接尽量简单\n\n团单宜指定一位接收人，并备好确认的茶品清单。针对实际饮品，可以询问适用的处理说明。再次订购时要重新确认供应与活动安排，不宜直接沿用旧记录。"
  },
  {
    slug: "tea-and-botanicals", title: "Botanical Tea Descriptions: Name the Ingredient", zhTitle: "看植物风味茶饮：先问原料名称",
    summary: "Separate a floral or herbal description from the actual ingredients listed for a drink.", zhSummary: "把花香、草本等描述，与饮品列出的实际原料分开看。", category: "Tea Ingredients", photo: "bright-tea-terraces-v2",
    en: "## A flavour word is a starting point\n\nFloral, herbal and botanical are broad descriptions. If you want to understand a cup, ask which ingredient the current description actually names. A decorative flower in artwork does not prove that flower is used.\n\n## Ask how it fits the drink\n\nCheck the listed tea base and other accompaniments. You may enjoy the aroma without wanting a particular texture, so describe these preferences separately when choosing.\n\n## Avoid filling gaps with benefit claims\n\nA plant name does not establish a medical or nutritional benefit for a prepared drink. This article is about reading a menu. QING YUN JIAN's current information and direct store confirmation are the appropriate sources for its own drink composition, rather than a general description of a plant.",
    zh: "## 风味词只是起点\n\n花香、草本、植物风味，都是广义描述。想了解一杯茶，应问清当前介绍实际列了哪种原料；画面里的装饰花朵，不能证明饮品使用该花。\n\n## 看它怎样参与搭配\n\n查看茶底及其他搭配。喜欢某种香气，未必喜欢某种触感，选茶时可以分别说明。\n\n## 不用功效宣传填补资料空缺\n\n植物名称不能证明调制饮品有医疗或营养效果。这篇文章帮助阅读菜单；了解青云间的实际搭配，应依据现行资料及门店确认，而不是一般植物说明。"
  },
  {
    slug: "tea-tasting-beginners", title: "Tea Tasting for Beginners: Five Personal Notes", zhTitle: "第一次认真品茶：五条自己的记录",
    summary: "A simple observation exercise that helps you remember what you enjoyed.", zhSummary: "用简单观察，记住自己喜欢的茶饮体验。", category: "Tea Culture", photo: "store-cups-photo-v3",
    en: "## Give yourself five prompts\n\nYou do not need a scoring sheet to learn from a cup. Try recording five observations in your own words.\n\n- What you notice in the aroma.\n- What you notice in the first sip.\n- How the liquid feels.\n- What remains after a sip.\n- Whether you would order it again.\n\n## Describe rather than diagnose\n\nThese notes describe your experience. They do not prove origin, ingredient amounts or professional quality grades. Two people can enjoy the same drink for different reasons.\n\n## Make the next comparison smaller\n\nChoose one thing to explore next: another texture, another listed tea base or another flavour. Keep the original drink name with your notes. This turns a tasting into a useful ordering reference instead of a competition to find the most elaborate vocabulary.",
    zh: "## 给自己五个观察提示\n\n不需要评分表，也能从一杯茶了解偏好。可以用自己的话记录五点。\n\n- 闻到什么。\n- 第一口注意到什么。\n- 液体入口的触感。\n- 喝下一口后留下什么。\n- 是否愿意再次点这杯。\n\n## 描述体验，不替产品作鉴定\n\n这些记录说明个人感受，不能证明产地、原料用量或专业等级。两个人可能因为不同原因喜欢同一杯。\n\n## 下一次少改一点\n\n挑一个想继续探索的元素：另一种触感、茶底或风味。茶名与记录一起保留，就能成为下次点单的实用参考，不必比赛谁用的词更复杂。"
  },
  {
    slug: "tea-pairing-desserts", title: "Tea with Dessert: Compare the Combination", zhTitle: "茶配甜点：比较组合的感觉",
    summary: "Test one dessert and one drink together, then record what you personally prefer.", zhSummary: "用一份甜点与一杯茶，试出自己喜欢的搭配。", category: "Tea Pairing", photo: "store-packaging-wide-v4",
    en: "## Name the dessert\n\nA cake, a fruit dessert and a pastry can create different impressions. Begin with the dessert you actually plan to eat, not a rule for all sweet foods.\n\n## Try the cup on its own first\n\nTake a sip, then taste the dessert, then return to the drink. Note whether the combination changes what you notice. You may prefer the tea alone or alongside the dessert; either observation is useful.\n\n## Plan sharing clearly\n\nIf friends are bringing desserts, agree whether everyone chooses their own drink or an organiser selects several options. Check current availability before collecting payment from friends. This is a tasting suggestion, not a QING YUN JIAN dessert menu or a promise of a packaged pairing.",
    zh: "## 先写清是哪份甜点\n\n蛋糕、水果甜点与酥点，可能带来不同感受。应从实际要吃的一份开始，不必为所有甜食定同一条规则。\n\n## 先单独喝一口\n\n先尝茶，再吃甜点，之后回到茶，记录组合有没有改变注意到的味道。可能更喜欢单独喝，也可能喜欢一起搭配，两种发现都有用。\n\n## 分享安排说清楚\n\n朋友带甜点聚会，可以先决定各人选茶，还是由负责人挑几款。向朋友收款之前，应确认现时供应。这是品尝建议，并不是青云间的甜点菜单或组合套餐承诺。"
  },
  {
    slug: "tea-pairing-spicy-food", title: "Choosing Tea with a Spicy Meal", zhTitle: "吃辣时选茶：按自己的体验搭配",
    summary: "Choose the actual drink and meal without treating a pairing as a remedy.", zhSummary: "针对实际餐点与茶饮选择，不把搭配当作功效保证。", category: "Tea Pairing", photo: "store-packaging-portrait-v4",
    en: "## Start with your own preference\n\nThink about the meal's flavours and what you like to drink alongside it. Some people want a contrasting flavour; others prefer a familiar cup. There is no universal pairing in this guide.\n\n## Do not promise a remedy\n\nA tea recommendation should not be presented as guaranteed relief from spice. This article offers a personal tasting exercise, not a physiological claim or health advice. Choose from the actual menu and check ingredients where needed.\n\n## Order for a mixed group\n\nIf people choose different dishes, avoid assuming they all want the same drink. Collect tea choices separately from food choices. For a planned office meal, add the meal's serving time to the group request so the team can discuss the arrangement.",
    zh: "## 从个人偏好开始\n\n想一想餐点的味道，以及自己习惯搭配什么。有些人喜欢风味对比，有些人喜欢熟悉的一杯；本指南没有人人适用的搭配规则。\n\n## 不承诺“解辣”功效\n\n推荐茶饮，不应写成一定能缓解辣感。这篇文章提供个人品尝方法，没有生理效果或健康建议。应从实际菜单选择，需要时确认原料。\n\n## 一群人吃饭时分别收集\n\n大家选不同餐点，不代表都想喝同一杯。茶饮选择可以与食物选择分开收集；计划办公室用餐时，可以在团单注明供餐时间，让团队商量安排。"
  },
  {
    slug: "jasmine-tea-food-pairing", title: "A Jasmine Drink with Food: Notice the Aroma", zhTitle: "茉莉茶饮配餐：留意香气怎样变化",
    summary: "A focused tasting exercise for exploring a floral drink alongside one dish.", zhSummary: "用一道菜，观察花香茶饮的个人品尝变化。", category: "Tea Pairing", photo: "store-cups-photo-v3",
    en: "## Pick one dish and one drink\n\nChoose a drink whose current description mentions jasmine and a dish you enjoy. Avoid changing the entire meal while comparing drinks; that makes your notes harder to interpret.\n\n## Follow one observation\n\nNotice the aroma before eating and what you notice after a mouthful. Describe whether the combination feels enjoyable to you. This does not establish a rule that jasmine must accompany a particular food.\n\n## Check the rest of the recipe\n\nA jasmine drink may include other listed elements that affect the pairing. Record the actual drink name, not just the tea word. Ingredient questions should be resolved with the store before ordering, especially when choosing cups for other people.",
    zh: "## 选一道菜与一杯茶\n\n选择当前介绍提到茉莉的茶饮，以及自己喜欢的一道菜。比较茶饮时，不必同时换整份餐点，否则不容易解释记录。\n\n## 只追踪一个感受\n\n留意吃之前闻到的香气，以及吃一口之后注意到什么，再说明自己是否喜欢组合。这不能证明茉莉一定要配某种食物。\n\n## 其他搭配也要看\n\n茉莉茶饮可能还有其他列出的元素，会影响组合。记录实际茶名，不只写“茉莉”。原料问题应在订购之前向门店确认，特别是替别人选茶时。"
  },
  {
    slug: "oolong-tea-food-pairing", title: "Oolong with Food: Compare the Actual Tea Drink", zhTitle: "乌龙茶饮配餐：比较具体那一杯",
    summary: "Keep the tea description, added flavours and meal in view when trying a pairing.", zhSummary: "把茶底介绍、搭配风味与实际餐点一起考虑。", category: "Tea Pairing", photo: "store-working-counter-v5",
    en: "## Do not pair by a broad name alone\n\nOolong is a starting point on a menu, not a complete description of a finished drink. Check the listed ingredients and whether you are choosing a sparkling or still style before planning a pairing.\n\n## Record the meal and the cup\n\nTry one combination and note whether you enjoyed it. Keep the dish and drink names together so you can repeat the experience or deliberately change one part next time.\n\n## Let guests keep their preferences\n\nFor a team lunch, offer the current menu instead of prescribing one pairing for everyone. An organiser can count each choice and ask about unresolved details. Availability and group fulfilment require confirmation; a pairing suggestion does not reserve drinks.",
    zh: "## 不只靠广义茶名搭配\n\n乌龙是菜单里的入门线索，并不是调制饮品的完整介绍。安排搭配前，应看列出的原料，以及选择的是气泡还是无气泡形式。\n\n## 茶与餐点一起记录\n\n试一个组合，记下是否喜欢。把菜名与茶名放在一起，之后可以重复体验，或有意识地只换其中一项。\n\n## 给每个人保留偏好\n\n团队午餐可以提供现行菜单，不必为全部人指定同一组合。负责人按选择统计，并询问未解决的细节。茶品供应与团单执行需要确认；搭配建议不等于已经预留饮品。"
  },
  {
    slug: "premium-tea-gift-guide", title: "Giving Tea from QING YUN JIAN: Check the Recipient and Timing", zhTitle: "送青云间茶饮：先想收礼人和时间",
    summary: "Plan a prepared-drink gift using the current menu, recipient preferences and confirmed arrangements.", zhSummary: "以现行菜单、收礼人偏好及确认的安排，准备一份茶饮心意。", category: "Premium Tea", photo: "store-packaging-portrait-v4",
    en: "## Choose for the recipient\n\nAsk what drink style they enjoy and whether any ingredient needs checking. A thoughtful choice reflects the recipient rather than the giver's favourite photograph. If it is a surprise, avoid guessing details that are important to them.\n\n## Confirm what is offered\n\nOur store photographs show cups and carry bags. They do not establish a gift-box service, vouchers, a delivery package or a special bundle. Check the current menu and ask the team about the arrangement you have in mind.\n\n## Make the handover part of the plan\n\nAgree who will receive the drinks and when. For several recipients, record names and choices before sending a group request. Wait for confirmation of availability, quotation and fulfilment before treating the gift arrangement as settled.",
    zh: "## 为收礼人选择\n\n先了解对方喜欢的饮品形式，以及有没有需要确认的原料。用心的选择，应围绕收礼人，而不是送礼人最喜欢的照片。想安排惊喜，也不宜猜测对方在意的重要细节。\n\n## 确认实际提供什么\n\n门店照片展示茶杯与提袋，不代表已有礼盒、礼券、配送套餐或特别组合。请看现行菜单，并向团队询问想安排的方式。\n\n## 交接也是计划的一部分\n\n约定谁接收、什么时候接收。多位收礼人可以先记录名字与选择，再提交团单。供应、报价与执行确认之后，再落实送茶安排。"
  },
  {
    slug: "tea-caffeine-explained", title: "Questions to Ask Before Ordering Tea When Caffeine Matters", zhTitle: "在意咖啡因时，点茶之前怎样问",
    summary: "Ask for product-specific information instead of estimating from a drink name or colour.", zhSummary: "询问具体产品资料，不凭茶名或颜色估算。", category: "Tea Ingredients", photo: "store-working-counter-v5",
    en: "## Ask about the specific drink\n\nGive the store the current drink name and ask what information is available about its tea base and preparation. A colour, photograph or broad category is not a measured caffeine result.\n\n## Distinguish a record from an estimate\n\nIf no measured figure is available, do not replace that gap with a confident number from a different tea or recipe. The information needs to match the actual serving you are considering.\n\n## Keep the scope clear\n\nThis is an ordering-information checklist, not advice on caffeine intake, pregnancy, sleep or a medical condition. The QING YUN JIAN menu does not provide a laboratory caffeine result for each cup. If you need a specific answer to make a purchase, seek confirmation before ordering.",
    zh: "## 针对具体茶品询问\n\n向门店提供当前茶名，询问茶底与制作方式有哪些可提供的资料。颜色、照片或广义分类，都不是咖啡因实测结果。\n\n## 分清记录与估算\n\n若没有实测数值，不应拿另一种茶或另一份配方的数字补上。资料需要对应正在考虑的实际份量与饮品。\n\n## 说明文章范围\n\n这是点单资料清单，不提供咖啡因摄入、孕期、睡眠或疾病建议。青云间菜单没有列出每杯的实验室咖啡因结果。购买需要具体答案时，请在订购之前确认。"
  },
  {
    slug: "tea-hydration-balanced-view", title: "Tea Drink Details: What the Menu Can and Cannot Tell You", zhTitle: "一杯茶的资料：菜单能告诉您什么",
    summary: "Use the menu for purchasing facts and avoid treating it as a personalised hydration plan.", zhSummary: "用菜单核对购买资料，不把它当作个人饮水计划。", category: "Tea Ingredients", photo: "store-packaging-wide-v4",
    en: "## Begin with the visible facts\n\nA useful drink page identifies the item, its description, price where available and current availability. These facts help with a purchase. They do not provide a personal daily fluid plan or establish a measured nutritional effect.\n\n## Ask for the information you need\n\nIf ingredients or serving details matter, state the question to the store. Do not assume a drink is equivalent to plain water because its appearance is clear or its description mentions tea.\n\n## Keep planning separate\n\nFor an event, organise cups according to the agreed request and ask about the actual handover. This article concerns product information and event planning. It makes no hydration recommendation or claim that a tea purchase fulfils somebody's personal needs.",
    zh: "## 先看页面列出的事实\n\n实用的茶品页应说明名称、介绍、可提供的价格及供应状态。这些能帮助购买，却没有提供个人每日饮水计划，也不能证明实测营养效果。\n\n## 提出需要知道的问题\n\n在意原料或份量，应把问题向门店说清楚。不能因为外观清澈或介绍提到茶，就假设饮品与白水相同。\n\n## 安排问题另外处理\n\n活动用茶按双方同意的清单组织，并确认实际交接。这篇文章讨论产品资料与活动准备，不提出饮水建议，也不声称购买茶饮能满足某人的个人需要。"
  },
  {
    slug: "modern-tea-ritual-singapore", title: "A Modern Tea Ritual: Make the Next Cup More Intentional", zhTitle: "现代日常茶时刻：让下一杯更有意思",
    summary: "Build a small personal habit around choosing, noticing and remembering a cup.", zhSummary: "围绕选茶、观察与记录，建立一个简单的日常茶时刻。", category: "Tea Lifestyle", photo: "bright-cloud-pavilion-v2",
    en: "## Choose a moment that already exists\n\nA lunch break or a conversation with a friend can be a place to enjoy tea. You do not need an elaborate ceremony or new equipment to make that moment your own.\n\n## Notice one thing\n\nChoose a single observation: the aroma, the texture or the flavour you enjoy. Put your impression into ordinary words. The purpose is attention to your own experience, not a claim that the drink will change your wellbeing.\n\n## Carry a preference forward\n\nRemember the drink name and one reason you liked it. Next time, return to that cup or explore a different choice from the current menu. QING YUN JIAN's Born to Ascend expresses aspiration; your everyday tea moment can remain as simple as a thoughtful choice.",
    zh: "## 找一个已经存在的时刻\n\n午餐休息、与朋友聊天，都可以成为享受茶的时间。不需要复杂仪式或添置工具，也能让这一刻属于自己。\n\n## 留意一件事\n\n挑一个观察：香气、触感，或喜欢的味道，用普通的话记下。重点是自己的体验，不是宣称饮品能改变身心状态。\n\n## 把偏好带到下一杯\n\n记住茶名与一个喜欢的原因。下次可以回到这杯，也可以从现行菜单探索另一款。青云间的 Born to Ascend 表达向上的志向；日常茶时刻，可以只是一个有意识的选择。"
  },
  {
    kind: "guide", slug: "complete-guide-sparkling-tea", title: "Sparkling Tea: From First Choice to Shared Order", zhTitle: "气泡茶指南：从第一杯到一起订茶",
    summary: "A decision path for texture, drink information, comparison and group planning.", zhSummary: "从触感、产品资料与个人比较，走到清楚的团单安排。", category: "Sparkling Tea", photo: "sparkling-tea-detail-v3",
    en: "## Start with texture\n\nSparkling tea combines tea and carbonation. If the bubbly sensation is what you want, begin there; then read the specific drink description to understand the rest of the choice. The category alone does not supply a recipe.\n\n## Move from category to actual cup\n\nOpen the current menu and shortlist a drink by its listed description. Check whether it is available, whether a displayed price has membership conditions and whether the details you need are recorded. Ask the store about anything unresolved. A photograph is useful for presentation but cannot establish ingredient amounts.\n\n## Compare with a purpose\n\nChoose one thing to explore, such as texture or a listed flavour. Record what you notice and whether you would order the same drink again. Personal notes help you select a second cup without pretending to provide a professional rating.\n\n## Extend the choice to a group\n\nCollect each person's preference and count cups by drink name. For a planned gathering, include the requested date, time and handover arrangement. A group request still needs confirmation of availability, quotation and fulfilment. Use the office and event guides for those steps.",
    zh: "## 从触感开始\n\n气泡茶把茶与气泡结合。喜欢气泡感觉，可以先从这里选，再看具体介绍了解其他搭配；类别本身不是配方。\n\n## 从类别走到实际那一杯\n\n打开现行菜单，按介绍挑选，核对供应状态、标示价格是否有会员条件，以及需要的细节有没有列出。未解决的问题向门店询问；照片能说明外观，不能证明原料用量。\n\n## 带一个目的比较\n\n可以只探索触感，或某一种列出的风味。记下注意到什么、是否愿意再点。个人记录能帮助第二次选茶，不需要写成专业评分。\n\n## 一群人订茶时\n\n收集偏好，按茶名统计杯数。计划聚会则要提供日期、时间与交接安排。团单仍需确认供应、报价及执行，可以继续阅读办公室与活动指南。"
  },
  {
    kind: "guide", slug: "complete-guide-chinese-tea", title: "Chinese Tea on a Modern Menu: A Beginner's Route", zhTitle: "现代菜单里的中国茶：入门阅读路线",
    summary: "Learn a basic category framework and use it without confusing tea types with finished drinks.", zhSummary: "认识基本茶类，再把分类与调制饮品的资料分开。", category: "Chinese Tea", photo: "bright-tea-terraces-v2", sources: [museum],
    en: "## Begin with a category framework\n\nThe Hong Kong Museum of Tea Ware introduces six processing-based categories: green, black, oolong, white, yellow and pu'er tea. Use that as a map for further learning, not as a claim that every shop offers all six.\n\n## Read three layers on a menu\n\nFirst look for the tea description. Next identify any listed accompaniments. Finally check the serving style. A milk tea, fruit tea or sparkling drink can combine these layers in different ways; one word cannot describe the whole purchase.\n\n## Ask a question that matches your aim\n\nIf you want to explore tea categories, ask which tea the drink lists. If you want a particular texture, ask about the serving style. If an ingredient matters, name it. These questions need different answers.\n\n## Choose one next step\n\nStart with a current drink description and keep the name with your tasting notes. Explore another listed choice later. This guide does not establish QING YUN JIAN's tea origins, grades or recipe specifications beyond the current product information.",
    zh: "## 先用分类作地图\n\n香港茶具文物馆按加工方式介绍绿茶、红茶、乌龙茶、白茶、黄茶与普洱茶六类。可以用它作为继续学习的地图，不代表每家店都供应六类。\n\n## 菜单分三层读\n\n先找茶的说明，再看列出的搭配，最后看饮用形式。奶茶、水果茶与气泡茶，可以把这些层次以不同方式组合，一个词不能说明整份购买。\n\n## 按自己的目的提问\n\n探索茶类，可以问饮品列的是哪种茶；在意触感，则问饮用形式；在意某种原料，则直接点名。不同问题需要不同答案。\n\n## 只选一个下一步\n\n从当前单款介绍开始，把茶名与品尝记录放在一起，再慢慢探索另一款。本指南没有在现行产品资料之外，确定青云间茶叶的产地、等级或配方规格。"
  },
  {
    kind: "guide", slug: "singapore-premium-tea-guide", title: "Buying Tea in Singapore: Information, Value and Occasion", zhTitle: "新加坡买茶指南：资料、价值与场合",
    summary: "A practical purchasing framework for a personal cup, a visit or an office request.", zhSummary: "从个人一杯、到店体验，到办公室申请的购买思路。", category: "Singapore Tea", photo: "store-welcome-v5", showStore: true,
    en: "## Define the purchase\n\nDecide whether you are buying one cup, planning a visit or organising drinks for others. Your questions will change accordingly. A personal flavour choice does not answer an organiser's questions about quantity and handover.\n\n## Compare information you can verify\n\nCheck descriptions, current availability and price conditions. Avoid treating an adjective such as premium as evidence of origin or quality. If a sourcing detail is important, ask for the actual information.\n\n## Include practical costs\n\nFor an individual purchase, check the relevant displayed price. For a group, review the quotation and any separate fulfilment charge before final agreement. This guide does not state a universal fair price or promise a discount.\n\n## Plan a QING YUN JIAN visit\n\nOur first store is at MacPherson Mall, Singapore. Use the managed address and opening information on the visit page, along with the map link, to plan your own route. Check the current menu before relying on an old promotion or photograph.",
    zh: "## 先确定这次购买的范围\n\n是一杯自饮、计划到店，还是替一群人订茶？问题会随场合改变。个人风味选择，不能回答负责人关于数量与交接的问题。\n\n## 比较可以核对的资料\n\n看介绍、供应状态与价格条件。“高级”这样的词不能证明来源或质量；在意来源时，应询问实际资料。\n\n## 实际费用一起看\n\n个人购买看相应标价；团单应在最终确认前核对报价与可能另外计算的执行费用。本指南不规定统一合理价格，也不承诺折扣。\n\n## 计划到青云间\n\n首家门店位于新加坡 MacPherson Mall。请用到店页面由后台管理的地址、营业资料及地图，规划自己的路线。旧活动或照片不能代替现行菜单。"
  },
  {
    kind: "guide", slug: "jasmine-tea-complete-guide", title: "Exploring Jasmine Drinks: A Menu and Tasting Guide", zhTitle: "探索茉莉茶饮：菜单与品尝指南",
    summary: "Build a clear shortlist using descriptions, personal aroma preferences and preparation questions.", zhSummary: "按茶饮介绍、花香偏好与制作问题，整理清楚的选择范围。", category: "Jasmine Tea", photo: "store-cups-photo-v3",
    en: "## Decide what interests you\n\nYou might be looking for a floral impression, a familiar tea word or a drink you tried previously. Name that starting point. It helps the team understand the question without assuming you want every jasmine drink to taste the same.\n\n## Read the whole description\n\nSeparate the listed tea from accompanying flavours and texture. A finished drink is not simply a plain tea with a new name. Confirm ingredients or offered adjustments if they affect your choice.\n\n## Make a short personal record\n\nNote the aroma you notice, the flavour of the first sip and whether you enjoy the texture. Keep these impressions separate from factual claims about sourcing or processing. Personal tasting cannot establish those facts.\n\n## Explore without guessing\n\nFor a second choice, change one aspect you want to compare. For a group, let people state their own preferences and record any questions before agreement. Current QING YUN JIAN menu data, rather than this guide, establishes which drinks are offered today.",
    zh: "## 说清为什么想试\n\n可能喜欢花香、认识这个茶名，或想找回以前喝过的一杯。先说明起点，能帮助团队理解问题，也不必假设所有茉莉茶饮都有相同味道。\n\n## 读完整份介绍\n\n茶、搭配风味与触感应分开看。调制饮品不只是给纯茶换个名字；影响选择的原料或选项，需要确认。\n\n## 写一份简短个人记录\n\n记下香气、第一口味道与是否喜欢触感。个人感受应与来源或加工事实分开，品尝本身不能证明这些资料。\n\n## 探索时不靠猜\n\n第二次可以只改变一个想比较的元素。团单让各人表达偏好，并在确认前记录问题。今天有哪些可售茶品，由青云间现行菜单确定，不由这篇指南决定。"
  },
  {
    kind: "guide", slug: "oolong-tea-complete-guide", title: "Exploring Oolong Drinks: From Description to Choice", zhTitle: "探索乌龙茶饮：从介绍走到选择",
    summary: "Use the tea description, flavour companions and serving style to organise an oolong comparison.", zhSummary: "用茶底说明、搭配风味与饮用形式，安排一次乌龙茶饮比较。", category: "Oolong Tea", photo: "store-working-counter-v5",
    en: "## Read beyond the word oolong\n\nThe category word starts a conversation. The particular drink description should provide the next layer of information. If a precise tea specification is not recorded, ask for it rather than borrowing one from another product.\n\n## Separate three decisions\n\nConsider the listed tea, any accompanying flavour and the serving texture independently. A fruit-led drink and a milk-based drink may be different purchases even if both descriptions mention oolong. Choose the experience you want today.\n\n## Compare with consistent notes\n\nRecord each actual drink name and what you enjoyed. Use ordinary words for aroma, taste and texture. Those notes guide a personal repeat purchase; they are not a laboratory result or a tea grade.\n\n## Organise multiple cups\n\nFor a team order, count by drink name and note any questions separately. Confirm the current list, quantities and quotation with the team. The guide does not guarantee particular origins, roast levels, recipes or availability.",
    zh: "## 不只读“乌龙”两个字\n\n类别名称是谈话起点，单款介绍应提供下一层资料。没有记录具体茶叶规格时，可以询问，不要借用另一款产品的说明。\n\n## 把三个决定分开\n\n分别考虑茶、搭配风味与饮用触感。即使都提到乌龙，水果风味饮品与奶类饮品也可能是不同选择。按今天想要的体验决定。\n\n## 用一致的方式记录\n\n写下实际茶名与喜欢的地方，用普通话描述香气、味道与触感。这些帮助个人回购，不是实验室结果或茶叶等级。\n\n## 多杯时按名称统计\n\n团单按茶名计算，把问题另行记录，再与团队确认现行清单、数量与报价。本指南不保证特定产地、焙火程度、配方或供应。"
  },
  {
    kind: "guide", slug: "tea-pairing-complete-guide", title: "Tea and Food Pairing: Build Your Own Comparison", zhTitle: "茶与食物搭配：建立自己的比较方法",
    summary: "Choose a dish, observe a combination and keep practical serving arrangements clear.", zhSummary: "选一道菜、观察组合，并把实际供应安排说清楚。", category: "Tea Pairing", photo: "store-packaging-wide-v4",
    en: "## Choose one real occasion\n\nBegin with lunch, dessert or a gathering you are actually planning. Name the food and when it will be served. A broad cuisine label is less useful than the dish in front of you.\n\n## Set up a personal comparison\n\nTry the drink alone, eat a mouthful, then return to the drink. Record whether you enjoyed the combination and which impression changed. This exercise describes preference; it does not establish digestive effects or universal pairing rules.\n\n## Change one part next time\n\nKeep the food and drink names with the notes. If you repeat the exercise, change one part so you know what you are comparing. You do not need numerical scores.\n\n## Plan sharing separately\n\nFor a meal with colleagues, collect drink choices and confirm the handover. The group-order form records a tea request; it does not provide an automatic food-and-drink catering package. Use the office and event checklists to prepare quantities, timing and quotation questions.",
    zh: "## 从实际场合开始\n\n可以是午餐、甜点或计划中的聚会。写清食物与供应时间，比一个笼统菜系名称更有用。\n\n## 安排个人比较\n\n先单独喝茶，再吃一口，之后回到茶，记录是否喜欢组合，以及哪个感受变化了。这说明个人偏好，不证明消化效果，也不是通用搭配规则。\n\n## 下次只改一部分\n\n茶名、菜名与记录一起保留，再试时只换其中一项，才知道正在比较什么。不需要数字评分。\n\n## 分享安排另外确认\n\n同事一起吃饭，应收集茶饮选择并确认交接。团单表格记录用茶申请，不是自动提供餐饮套餐；办公室与活动清单可以帮助整理数量、时间与报价问题。"
  },
  {
    kind: "guide", slug: "healthy-tea-beverages-guide", title: "Drink Information Checklist: Ingredients, Options and Claims", zhTitle: "茶饮资料清单：原料、选项与宣传",
    summary: "A purchasing guide to asking clear questions, with no nutritional ranking or medical recommendation.", zhSummary: "帮助提出清楚的购买问题，不作营养排名或医疗建议。", category: "Tea Ingredients", photo: "store-working-counter-v5",
    en: "## Identify the claim you are reading\n\nA drink can be described by flavour, appearance, ingredients or a claimed benefit. These are different types of information. Ask what supports a factual claim rather than treating every appealing word as a product specification.\n\n## Prepare a question list\n\n- What does the current description list?\n- Which details are documented for this drink?\n- Which adjustments are actually offered?\n- Does the price have membership or promotion conditions?\n- What remains to be confirmed before purchase?\n\n## Avoid unsupported comparisons\n\nDifferent categories or sweetness settings do not, by themselves, establish measured nutritional differences. A claim should concern the actual product and serving. This guide does not rate drinks as healthier or advise on a personal health condition.\n\n## Use the current information\n\nQING YUN JIAN's menu and drink pages provide purchasing information. Ask the store when a required answer is absent. For a group, record the unresolved question before final agreement instead of making an assumption on someone else's behalf.",
    zh: "## 先分清正在看的宣传\n\n饮品可以描述风味、外观、原料或所谓功效，这些是不同信息。事实性说法应有对应依据，不是所有好听的词都属于产品规格。\n\n## 准备问题清单\n\n- 当前介绍列出什么？\n- 这款有哪些已记录的资料？\n- 实际可以提供哪些调整？\n- 价格是否有会员或活动条件？\n- 购买之前还需要确认什么？\n\n## 避免没有依据的比较\n\n类别或甜度设置不同，不能单凭这一点证明实测营养差异。说法应对应实际产品与份量。本指南不作健康程度排名，也不提供个人疾病建议。\n\n## 用现行资料决定\n\n青云间菜单与茶品页提供购买资料，缺少必要答案时可以询问门店。团单应在最终确认前记录问题，不要替别人作假设。"
  },
  {
    kind: "guide", slug: "tea-culture-modern-singapore-guide", title: "QING YUN JIAN in Singapore: Tea, Design and Daily Life", zhTitle: "新加坡的青云间：茶、设计与日常",
    summary: "Explore the approved brand direction and its practical connection to visits and shared tea.", zhSummary: "认识品牌方向，以及它与到店、分享茶饮的实际联系。", category: "Tea Culture", photo: "store-interior-photo-v3", showStore: true,
    en: "## Begin with the brand's own context\n\nQING YUN JIAN originated in Singapore and was founded in 2026. Its first store is at MacPherson Mall. Modern Oriental tea is the brand direction, not a claim to represent every tea tradition or the whole history of Singapore tea.\n\n## Read the symbols carefully\n\nThe Pegasus expresses aspiration and upward movement. Born to Ascend is approved brand language, while Sparkling Tea Reimagined is the core English brand line. These meanings do not establish a recipe or a promised personal outcome.\n\n## Bring the idea into a visit\n\nThe menu offers the practical next step: read a description, check availability and choose a cup. Our Story provides the approved brand narrative. The visit page supplies managed store details so a story does not become the source for opening hours.\n\n## Share tea with a clear arrangement\n\nFor an office or gathering, collect choices and send a group request. The team confirms the quotation and handover. This gives the brand's contemporary direction an everyday use without inventing historical events or customer testimonials.",
    zh: "## 从品牌自己的背景开始\n\n青云间源自新加坡，创立于 2026 年，首家门店位于 MacPherson Mall。“现代东方茶”是品牌方向，不宣称代表所有茶传统或整个新加坡茶史。\n\n## 正确理解象征\n\n飞马表达志向与向上升腾。Born to Ascend 是品牌用语，Sparkling Tea Reimagined 是核心英文品牌主张。这些意义不能证明配方，也不是个人结果的承诺。\n\n## 把想法带到一次到店\n\n菜单提供实际下一步：读介绍、查供应，再选一杯。“我们的故事”提供已确认的品牌叙述；到店页面提供后台管理的门店资料，营业时间不由故事文章决定。\n\n## 用清楚安排分享茶\n\n办公室或聚会可以收集选择，提交团单，再由团队确认报价与交接。这样把品牌方向放进日常使用，无需编造历史事件或顾客见证。"
  },
  {
    kind: "guide", slug: "tea-ingredients-complete-guide", title: "Reading a Tea Drink: Base, Flavour, Texture and Options", zhTitle: "读懂一杯茶饮：茶底、风味、触感与选项",
    summary: "Organise the product information you need before choosing or requesting several cups.", zhSummary: "选茶或申请多杯之前，把需要的产品资料整理清楚。", category: "Tea Ingredients", photo: "store-packaging-portrait-v4",
    en: "## Start with the listed tea\n\nRead the description for the named tea base, where one is provided. Do not treat a poetic drink name as a source record. If a specification is absent, ask for the current information.\n\n## Identify accompanying elements\n\nLook separately for listed fruit, milk, floral elements or inclusions. A flavour name may not describe the form or amount of an ingredient. An image can help you recognise presentation, but it does not establish the complete recipe.\n\n## Check texture and options\n\nFind out whether the drink offers the style you want and which adjustments can be made. Confirm each question for the specific item rather than borrowing the answer from another drink.\n\n## Make a clear group list\n\nRecord names and quantities first. Add ingredient questions and requested adjustments separately, identifying the affected cups. The team needs to confirm what can be arranged. No ingredient quantity, allergen assurance or nutritional result is invented in this guide.",
    zh: "## 从列出的茶开始\n\n查看介绍有没有说明茶底，诗意茶名不能代替产品记录。规格没有列出时，可以询问现行资料。\n\n## 找出其他搭配\n\n水果、奶、花香元素或配料可以分别看。风味名称未必说明原料形式与用量；照片能帮助认识外观，不能证明完整配方。\n\n## 核对触感与选项\n\n确认是否有想要的饮用形式，以及能作哪些调整。每款应单独询问，不能借用另一款的答案。\n\n## 写清团单清单\n\n先记录茶名与数量，再另列原料问题、调整要求及涉及哪些杯。能否安排由团队确认。本指南没有编造原料用量、过敏原保证或营养结果。"
  },
  {
    kind: "guide", slug: "student-tea-wellbeing-guide", title: "Tea for a Student Gathering: Budget and Order Checklist", zhTitle: "学生聚会订茶：预算与点单清单",
    summary: "Prepare an affordable, organised enquiry using current prices, named choices and confirmed arrangements.", zhSummary: "按现价、个人选择与确认的安排，整理一份清楚的聚会用茶申请。", category: "Tea Lifestyle", photo: "store-interior-photo-v3",
    en: "## Agree who is organising\n\nChoose one contact person and decide whether everyone picks a drink or the organiser proposes a shortlist. Record the expected cups separately from headcount so nobody assumes the two numbers are identical.\n\n## Work from current prices\n\nUse the current menu and read any promotion's dates and eligibility. Old student posters do not establish a current offer. A member price should not be budgeted for everybody without checking the conditions.\n\n## Prepare the request\n\nRecord drink names, quantities, requested date and time, contact details and collection or delivery enquiry. Add venue information where relevant. Ingredient questions should be raised before agreement, not guessed by the organiser.\n\n## Wait for the arrangement to be confirmed\n\nThe group form does not take payment or reserve a slot automatically. The team confirms the quotation and fulfilment. This is an event-purchase guide; it does not claim that tea improves study, sleep or wellbeing. For a larger event, continue with the event checklist.",
    zh: "## 先决定谁负责\n\n选一位联络人，并决定各人选茶，还是负责人提供选择范围。预计杯数与人数分开记录，不要假设两者一定相同。\n\n## 用现行价格作预算\n\n查看当前菜单，阅读活动日期及条件。旧学生海报不能证明现时优惠；会员价也不能未核实条件就套用到所有人。\n\n## 准备申请资料\n\n记录茶名、数量、日期、时间、联络方式，以及自取或配送询问。需要时提供场地说明。原料问题应在确认之前提出，不由负责人猜测。\n\n## 等安排获确认\n\n团单表格不收取付款，也不自动预留时段。团队仍须确认报价与执行。这是一份活动购买指南，不宣称茶能改善学习、睡眠或身心状态。较大型活动可以继续使用活动清单。"
  }
];

export const reviewedEntries: ContentEntry[] = drafts.map(draft => ({
  kind: draft.kind || "article", slug: draft.slug, title: draft.title,
  description: draft.summary, heroImage: `/assets/story/${draft.photo}.webp`,
  heroAlt: draft.photo.startsWith("store-") ? `QING YUN JIAN store photograph accompanying ${draft.title}` : `Illustration accompanying ${draft.title}`,
  author: { name: "QING YUN JIAN Editorial Team", role: "Brand editorial team", bio: "Practical tea, visiting and group-order guides from QING YUN JIAN in Singapore." },
  publishedAt: "2026-10-05", updatedAt: "2026-10-05",
  readingTime: Math.max(1, Math.ceil(draft.en.split(/\s+/).length / 220)),
  keywords: [draft.title, draft.zhTitle, "QING YUN JIAN", "青云间"],
  category: draft.category, categorySlug: draft.category.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  markdown: draft.en, faq: [], sources: draft.sources,
  relatedSlugs: draft.kind === "guide" ? ["first-visit-tea-menu-guide", "office-tea-group-orders-singapore", "event-tea-order-checklist"] : ["sparkling-tea-singapore-guide", "macpherson-tea-guide", "first-visit-tea-menu-guide"],
  showMenu: true, showStore: draft.showStore,
  zh: { title: draft.zhTitle, description: draft.zhSummary,
    heroAlt: draft.photo.startsWith("store-") ? `青云间门店实拍，配合《${draft.zhTitle}》` : `《${draft.zhTitle}》的示意配图`,
    markdown: draft.zh, faq: [] }
}));
