import Link from "next/link";
import { requireUser } from "@/lib/data";
import { createServiceClient } from "@/lib/supabase/admin";
import { GROUP_ORDER_PROVIDER, type GroupOrderRecord } from "@/lib/group-orders";
export const dynamic = "force-dynamic";
export const metadata = { robots: { index: false, follow: false, nocache: true }, title: "Guest Account | QING YUN JIAN" };
export default async function GuestAccount({ params, searchParams }: { params: { locale: string }; searchParams: { page?: string } }) {
  const user = await requireUser(params.locale); const zh = params.locale === "zh";
  const page = Math.max(1, Math.min(10000, Math.floor(Number(searchParams.page) || 1)));
  const { data, error, count } = await createServiceClient().from("webhook_events").select("payload_json", { count: "exact" }).eq("provider", GROUP_ORDER_PROVIDER).eq("payload_json->>authUserId", user.id).order("received_at", { ascending: false }).range((page - 1) * 25, page * 25 - 1);
  if (error) throw new Error("Your order history could not be loaded.");
  const labels = zh ? { requested: "等待报价", quoted: "已报价，等待确认", confirmed: "已确认", fulfilled: "已完成", cancelled: "已取消" } : { requested: "Awaiting quotation", quoted: "Quoted · awaiting confirmation", confirmed: "Confirmed", fulfilled: "Fulfilled", cancelled: "Cancelled" };
  return <main className="min-h-screen bg-paper px-5 py-12 text-forest"><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">{zh ? "免费访客账号" : "Free guest account"}</p><h1 className="mt-4 font-serif text-4xl">{zh ? "我的团单与报价" : "My group orders & quotations"}</h1><p className="mt-4 break-all text-forest/70">{user.email}</p><p className="mt-3 text-sm leading-6 text-forest/65">{zh ? "这里显示登录后提交的团单。无需购买付费会员；报价不代表已付款。之前未登录提交的需求不会仅凭邮箱自动关联，请凭订单编号联系门店。" : "Orders submitted while signed in appear here. No paid membership is required. A quotation is not a payment receipt. Earlier requests submitted without signing in are not automatically linked by email; contact the store with your reference."}</p><Link href={`/${params.locale}/group-orders`} className="mt-6 inline-block rounded-full bg-forest px-6 py-3 font-bold text-white">{zh ? "提交新团单 →" : "Start a group order →"}</Link><div className="mt-8 space-y-5">{(data || []).map((row, index) => { const order = row.payload_json as GroupOrderRecord; return <article key={index} className="rounded-3xl bg-white p-6 shadow-soft"><p className="text-sm font-bold">{labels[order.status]} · {order.totalCups} {zh ? "杯" : "cups"}</p><p className="mt-2 break-all font-mono text-xs text-forest/60">{order.reference}</p><p className="mt-4">{order.date} · {order.time} SGT · {order.fulfilment === "collection" ? order.storeName : (zh ? "配送" : "Delivery")}</p><ul className="mt-4 text-sm leading-7">{order.items.map(item => <li key={item.id}>{item.name} × {item.quantity}</li>)}</ul>{order.quote && <div className="mt-4 rounded-xl bg-paper p-4 text-sm leading-7"><p>{zh ? "饮品" : "Drinks"}: S${order.quote.drinks.toFixed(2)}</p><p>{zh ? "配送费" : "Delivery fee"}: S${order.quote.delivery.toFixed(2)}</p><p className="font-bold">{zh ? "总金额" : "Total"}: S${order.quote.total.toFixed(2)}</p></div>}</article>; })}{!data?.length && <p className="rounded-3xl bg-white p-6">{zh ? "尚无登录后提交的团单。" : "No group orders submitted while signed in yet."}</p>}</div><nav className="mt-7 flex gap-5">{page > 1 && <Link href={`?page=${page - 1}`} className="underline">{zh ? "上一页" : "Previous"}</Link>}{page * 25 < (count || 0) && <Link href={`?page=${page + 1}`} className="underline">{zh ? "下一页" : "Next"}</Link>}</nav></div></main>;
}
