import Link from "next/link";
import { AdminNavigation } from "@/components/admin/admin-navigation";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/data";
import { createServiceClient } from "@/lib/supabase/admin";
import { GROUP_ORDER_PROVIDER, orderStatuses, type GroupOrderRecord } from "@/lib/group-orders";
import { updateGroupOrder } from "./actions";
export const dynamic = "force-dynamic";
export default async function GroupOrderAdmin({ params, searchParams }: { params: { locale: string }; searchParams: { page?: string; error?: string; saved?: string } }) {
  const { role } = await requireAdmin(params.locale);
  if (role !== "super_admin" && role !== "manager") redirect(`/${params.locale}/admin`);
  const page = Math.max(1, Math.min(10000, Number(searchParams.page) || 1));
  const { data, error, count } = await createServiceClient().from("webhook_events").select("id,payload_json", { count: "exact" }).eq("provider", GROUP_ORDER_PROVIDER).order("received_at", { ascending: false }).range((page - 1) * 25, page * 25 - 1);
  if (error) throw new Error("Group order records could not be loaded.");
  const field = "mt-2 min-h-11 w-full rounded-xl border border-forest/20 bg-paper p-3";
  return <main className="min-h-screen bg-paper px-5 py-12 text-forest"><div className="mx-auto max-w-5xl"><AdminNavigation locale={params.locale === "zh" ? "zh" : "en"} /><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-gold">Customer requests · Operations</p><h1 className="mt-3 font-serif text-4xl md:text-5xl">Group orders</h1><p className="mt-4 text-forest/70">{count || 0} requests. Contact customers to agree the quote, availability and payment arrangements. Status changes do not send email or collect payment. Confirm only after recording customer acceptance.</p>{searchParams.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-800">{searchParams.error}</p>}{searchParams.saved && <p role="status" className="mt-5 rounded-xl bg-green-50 p-4">Changes saved.</p>}
    <div className="mt-8 space-y-6">{(data || []).map(row => { const order = row.payload_json as GroupOrderRecord; return <article key={row.id} className="rounded-3xl border border-forest/10 bg-white p-6 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{order.name} · {order.totalCups} cups</h2><p className="mt-2 break-all font-mono text-xs text-forest/60">{order.reference}</p></div><span className="rounded-full bg-[#eaf0e3] px-4 py-2 text-sm font-bold">{order.status}</span></div><div className="mt-5 grid gap-4 text-sm leading-6 md:grid-cols-2"><div><p>{order.organisation || "Personal gathering"} · {order.intent === "quote" ? "Quotation enquiry" : "Order request"}</p><p><a className="underline" href={`mailto:${order.email}`}>{order.email}</a> · {order.phone}</p><p>Submitted {new Date(order.createdAt).toLocaleString("en-SG", { timeZone: "Asia/Singapore" })} SGT</p></div><div><p>Preferred: {order.date} · {order.time} SGT</p><p>{order.fulfilment === "collection" ? `Collection at ${order.storeName}` : `Delivery: ${order.address}`}</p><p className="whitespace-pre-wrap">Customer notes: {order.notes || "—"}</p></div></div><ul className="mt-5 rounded-xl bg-paper p-4 text-sm">{order.items.map(item => <li key={item.id} className="flex justify-between py-1"><span>{item.name}</span><strong>{item.quantity} cups</strong></li>)}</ul>
    <details className="mt-6"><summary className="cursor-pointer font-bold">Quote & manage request {order.quote ? `· S$${order.quote.total.toFixed(2)}` : ""}</summary><form action={updateGroupOrder} className="mt-5"><input type="hidden" name="locale" value={params.locale} /><input type="hidden" name="id" value={row.id} /><input type="hidden" name="version" value={order.version} /><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-bold">Status<select name="status" className={field} defaultValue={order.status}>{orderStatuses.map(s => <option key={s} value={s}>{s}</option>)}</select></label><label className="text-sm font-bold">Drinks amount (SGD)<input type="number" name="drinks" min="0" max="100000" step="0.01" className={field} defaultValue={order.quote?.drinks || 0} required /></label><label className="text-sm font-bold">Delivery fee (SGD)<input type="number" name="delivery" min="0" max="100000" step="0.01" className={field} defaultValue={order.quote?.delivery || 0} required /></label></div><label className="mt-4 block text-sm font-bold">Internal notes / customer acceptance<textarea className={field} name="notes" rows={3} maxLength={2000} defaultValue={order.internalNotes} /></label><button className="mt-4 rounded-full bg-forest px-6 py-3 font-bold text-white" type="submit">Save changes</button></form><div className="mt-5 border-t border-forest/10 pt-4 text-xs text-forest/65"><p className="font-bold">Change history</p>{order.history.map((h, index) => <p className="mt-2 whitespace-pre-wrap" key={index}>{new Date(h.at).toLocaleString("en-SG", { timeZone: "Asia/Singapore" })} SGT · {h.status} · {h.note || "No note"}</p>)}</div></details></article>; })}{!data?.length && <p className="rounded-2xl bg-white p-8">No group order requests yet.</p>}</div><nav aria-label="Order pages" className="mt-8 flex gap-5">{page > 1 && <Link href={`?page=${page - 1}`} className="underline">Previous</Link>}{page * 25 < (count || 0) && <Link href={`?page=${page + 1}`} className="underline">Next</Link>}</nav></div></main>;
}
