import type { Metadata } from "next";
import Link from "next/link";
import type { Locale } from "@/lib/constants";
import { getPublicPromotions } from "@/lib/promotions";
import { buildSearchIndex, searchRecords } from "@/lib/content/search";
import { createPageMetadata } from "@/lib/seo";
import { Breadcrumb } from "@/components/content/breadcrumb";

export function generateMetadata({ params }: { params: { locale: Locale } }): Metadata { return createPageMetadata({ locale: params.locale, path: "/search", title: params.locale === "zh" ? "搜索茶饮文章与指南 | 青云间" : "Search Tea Articles and Guides | Qing Yun Jian", description: "Search Qing Yun Jian tea articles, guides, frequently asked questions and public promotions.", keywords: ["Qing Yun Jian search", "tea articles", "tea guides"], includeLanguageAlternates: true }); }
export default async function SearchPage({ params, searchParams }: { params: { locale: Locale }; searchParams?: { q?: string } }) { const query = searchParams?.q?.trim() ?? ""; const promotions = await getPublicPromotions(); const results = searchRecords(buildSearchIndex(params.locale, promotions), query); return <main className="bg-[#f8f5ed]"><div className="mx-auto max-w-5xl px-5 py-16 md:px-8 md:py-24"><Breadcrumb locale={params.locale} items={[{ name: params.locale === "zh" ? "首页" : "Home" }, { name: params.locale === "zh" ? "搜索" : "Search", path: "/search" }]} /><h1 className="mt-10 font-serif text-6xl font-semibold text-forest md:text-8xl">{params.locale === "zh" ? "搜索青云间。" : "Search Qing Yun Jian."}</h1><form action={`/${params.locale}/search`} className="mt-10 flex flex-col gap-3 sm:flex-row" role="search"><label className="sr-only" htmlFor="content-search">Search articles, guides, FAQs and promotions</label><input id="content-search" className="focus-ring min-h-12 flex-1 border border-forest/15 bg-white px-5 text-forest" defaultValue={query} name="q" placeholder={params.locale === "zh" ? "搜索茶品、原料或指南" : "Search tea, ingredients or guides"} type="search" /><button className="focus-ring min-h-12 rounded-full bg-forest px-7 text-sm font-bold text-white" type="submit">{params.locale === "zh" ? "搜索" : "Search"}</button></form>{query ? <p className="mt-8 text-sm font-semibold text-forest/50">{params.locale === "zh" ? `找到 ${results.length} 项与“${query}”相关的结果` : `${results.length} results for “${query}”`}</p> : <p className="mt-8 text-forest/60">{params.locale === "zh" ? "搜索茶饮文章、指南、常见问题与现行活动。" : "Search the editorial library, FAQs and current public promotions."}</p>}<div className="mt-8 grid gap-4">{results.map((result) => <Link key={result.id} className="bg-white p-6 shadow-[0_18px_50px_rgba(10,24,20,0.06)]" href={result.href}><p className="text-xs font-bold uppercase tracking-[0.16em] text-gold">{params.locale === "zh" ? ({ Article: "文章", Guide: "指南", FAQ: "常见问题", Promotion: "活动" })[result.type] : result.type}</p><h2 className="mt-3 font-serif text-3xl font-semibold text-forest">{result.title}</h2><p className="mt-3 leading-7 text-forest/60">{result.description}</p></Link>)}</div></div></main>; }
