"use client";
import { useFormState, useFormStatus } from "react-dom";
import { registerGuest } from "@/app/[locale]/guest/register/actions";
function Submit({ zh }: { zh: boolean }) { const { pending } = useFormStatus(); return <button className="min-h-12 rounded-full bg-forest px-6 py-3 font-bold text-white disabled:opacity-50" disabled={pending}>{pending ? (zh ? "正在注册…" : "Creating account…") : (zh ? "创建免费访客账号" : "Create free guest account")}</button>; }
export function GuestRegisterForm({ locale }: { locale: string }) {
  const [state, action] = useFormState(registerGuest, { ok: false, message: "" }); const zh = locale === "zh";
  const field = "mt-2 min-h-12 w-full rounded-xl border border-forest/20 bg-paper p-3";
  return <form action={action} className="grid gap-5 rounded-3xl bg-white p-6 shadow-soft"><input name="locale" type="hidden" value={locale} /><label className="font-bold">{zh ? "姓名" : "Name"}<input className={field} name="name" required minLength={2} maxLength={100} autoComplete="name" /></label><label className="font-bold">{zh ? "电子邮箱" : "Email"}<input className={field} name="email" type="email" required maxLength={200} autoComplete="email" /></label><label className="font-bold">{zh ? "WhatsApp 联系号码" : "WhatsApp contact number"}<input className={field} name="phone" type="tel" required minLength={7} maxLength={30} autoComplete="tel" placeholder="+65 9123 4567" /></label><label className="font-bold">{zh ? "密码（至少8位）" : "Password (at least 8 characters)"}<input className={field} name="password" type="password" required minLength={8} maxLength={128} autoComplete="new-password" /></label><label className="flex gap-3 text-sm leading-6"><input type="checkbox" name="privacy" required /><span>{zh ? "我同意按隐私政策处理账号及订单资料。" : "I agree to the handling of account and order details under the privacy policy."} <a className="underline" href={`/${locale}/privacy`}>{zh ? "隐私政策" : "Privacy policy"}</a></span></label><div className="hidden" aria-hidden="true"><input name="website" tabIndex={-1} autoComplete="off" /></div>{state.message && <p role="status" className={state.ok ? "rounded-xl bg-green-50 p-4 text-sm" : "rounded-xl bg-red-50 p-4 text-sm text-red-800"}>{state.message}</p>}<Submit zh={zh} /><a href={`/${locale}/login?returnTo=/${locale}/guest`} className="text-sm underline">{zh ? "已有账号？登录" : "Already have an account? Sign in"}</a></form>;
}
